# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_VR.ui'
#
# Created: Mon Sep 26 17:54:35 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(745, 640)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 751, 531))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.loadWind = QtGui.QCheckBox(self.tab)
        self.loadWind.setGeometry(QtCore.QRect(30, 20, 99, 22))
        self.loadWind.setObjectName(_fromUtf8("loadWind"))
        self.loadOdour = QtGui.QCheckBox(self.tab)
        self.loadOdour.setGeometry(QtCore.QRect(30, 60, 99, 22))
        self.loadOdour.setObjectName(_fromUtf8("loadOdour"))
        self.loadTrajectory = QtGui.QCheckBox(self.tab)
        self.loadTrajectory.setGeometry(QtCore.QRect(30, 100, 99, 22))
        self.loadTrajectory.setObjectName(_fromUtf8("loadTrajectory"))
        self.imposeStimulus = QtGui.QCheckBox(self.tab)
        self.imposeStimulus.setGeometry(QtCore.QRect(30, 140, 141, 22))
        self.imposeStimulus.setObjectName(_fromUtf8("imposeStimulus"))
        self.loadingString = QtGui.QLineEdit(self.tab)
        self.loadingString.setGeometry(QtCore.QRect(210, 20, 113, 27))
        self.loadingString.setObjectName(_fromUtf8("loadingString"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(330, 20, 101, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.gain = QtGui.QSlider(self.tab)
        self.gain.setGeometry(QtCore.QRect(210, 58, 111, 21))
        self.gain.setMaximum(25)
        self.gain.setProperty("value", 7)
        self.gain.setOrientation(QtCore.Qt.Horizontal)
        self.gain.setObjectName(_fromUtf8("gain"))
        self.lcdNumber = QtGui.QLCDNumber(self.tab)
        self.lcdNumber.setGeometry(QtCore.QRect(250, 50, 121, 51))
        self.lcdNumber.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdNumber.setLineWidth(1)
        self.lcdNumber.setMidLineWidth(0)
        self.lcdNumber.setProperty("intValue", 7)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(380, 60, 68, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.settingsFile = QtGui.QLineEdit(self.tab)
        self.settingsFile.setGeometry(QtCore.QRect(482, 460, 113, 27))
        self.settingsFile.setObjectName(_fromUtf8("settingsFile"))
        self.jsonBtn = QtGui.QPushButton(self.tab)
        self.jsonBtn.setGeometry(QtCore.QRect(610, 460, 111, 27))
        self.jsonBtn.setObjectName(_fromUtf8("jsonBtn"))
        self.maxSpeed = QtGui.QDoubleSpinBox(self.tab)
        self.maxSpeed.setGeometry(QtCore.QRect(210, 110, 62, 27))
        self.maxSpeed.setObjectName(_fromUtf8("maxSpeed"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(280, 110, 81, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.disabledFly = QtGui.QCheckBox(self.tab)
        self.disabledFly.setGeometry(QtCore.QRect(30, 180, 141, 22))
        self.disabledFly.setObjectName(_fromUtf8("disabledFly"))
        self.label_155 = QtGui.QLabel(self.tab)
        self.label_155.setGeometry(QtCore.QRect(280, 150, 81, 17))
        self.label_155.setObjectName(_fromUtf8("label_155"))
        self.speed = QtGui.QDoubleSpinBox(self.tab)
        self.speed.setGeometry(QtCore.QRect(210, 150, 62, 27))
        self.speed.setObjectName(_fromUtf8("speed"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.fly = QtGui.QLineEdit(self.tab_2)
        self.fly.setGeometry(QtCore.QRect(20, 30, 113, 27))
        self.fly.setObjectName(_fromUtf8("fly"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(150, 30, 68, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(150, 70, 68, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.emergence = QtGui.QDateEdit(self.tab_2)
        self.emergence.setGeometry(QtCore.QRect(20, 110, 110, 27))
        self.emergence.setObjectName(_fromUtf8("emergence"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(150, 110, 81, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.windQuad = QtGui.QLineEdit(self.tab_2)
        self.windQuad.setGeometry(QtCore.QRect(20, 150, 113, 27))
        self.windQuad.setObjectName(_fromUtf8("windQuad"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(150, 150, 71, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(150, 190, 81, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.odourQuad = QtGui.QLineEdit(self.tab_2)
        self.odourQuad.setGeometry(QtCore.QRect(20, 190, 113, 27))
        self.odourQuad.setObjectName(_fromUtf8("odourQuad"))
        self.odour1 = QtGui.QLineEdit(self.tab_2)
        self.odour1.setGeometry(QtCore.QRect(300, 30, 113, 27))
        self.odour1.setObjectName(_fromUtf8("odour1"))
        self.odourBtn1 = QtGui.QPushButton(self.tab_2)
        self.odourBtn1.setGeometry(QtCore.QRect(430, 30, 111, 27))
        self.odourBtn1.setObjectName(_fromUtf8("odourBtn1"))
        self.odour2 = QtGui.QLineEdit(self.tab_2)
        self.odour2.setGeometry(QtCore.QRect(300, 70, 113, 27))
        self.odour2.setObjectName(_fromUtf8("odour2"))
        self.odourBtn2 = QtGui.QPushButton(self.tab_2)
        self.odourBtn2.setGeometry(QtCore.QRect(430, 70, 111, 27))
        self.odourBtn2.setObjectName(_fromUtf8("odourBtn2"))
        self.odour3 = QtGui.QLineEdit(self.tab_2)
        self.odour3.setGeometry(QtCore.QRect(300, 110, 113, 27))
        self.odour3.setObjectName(_fromUtf8("odour3"))
        self.odourBtn3 = QtGui.QPushButton(self.tab_2)
        self.odourBtn3.setGeometry(QtCore.QRect(430, 110, 111, 27))
        self.odourBtn3.setObjectName(_fromUtf8("odourBtn3"))
        self.odour4 = QtGui.QLineEdit(self.tab_2)
        self.odour4.setGeometry(QtCore.QRect(300, 150, 113, 27))
        self.odour4.setObjectName(_fromUtf8("odour4"))
        self.odourBtn4 = QtGui.QPushButton(self.tab_2)
        self.odourBtn4.setGeometry(QtCore.QRect(430, 150, 111, 27))
        self.odourBtn4.setObjectName(_fromUtf8("odourBtn4"))
        self.race = QtGui.QComboBox(self.tab_2)
        self.race.setGeometry(QtCore.QRect(20, 70, 111, 27))
        self.race.setObjectName(_fromUtf8("race"))
        self.race.addItem(_fromUtf8(""))
        self.race.addItem(_fromUtf8(""))
        self.race.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.generateWorld = QtGui.QCheckBox(self.tab_4)
        self.generateWorld.setGeometry(QtCore.QRect(20, 20, 141, 22))
        self.generateWorld.setObjectName(_fromUtf8("generateWorld"))
        self.loadHUD = QtGui.QCheckBox(self.tab_4)
        self.loadHUD.setGeometry(QtCore.QRect(20, 50, 141, 22))
        self.loadHUD.setObjectName(_fromUtf8("loadHUD"))
        self.loadWorld = QtGui.QCheckBox(self.tab_4)
        self.loadWorld.setGeometry(QtCore.QRect(20, 80, 141, 22))
        self.loadWorld.setObjectName(_fromUtf8("loadWorld"))
        self.replayWorld = QtGui.QCheckBox(self.tab_4)
        self.replayWorld.setGeometry(QtCore.QRect(20, 110, 141, 22))
        self.replayWorld.setObjectName(_fromUtf8("replayWorld"))
        self.skyMap = QtGui.QLineEdit(self.tab_4)
        self.skyMap.setGeometry(QtCore.QRect(220, 10, 113, 27))
        self.skyMap.setObjectName(_fromUtf8("skyMap"))
        self.skyMapNull = QtGui.QLineEdit(self.tab_4)
        self.skyMapNull.setGeometry(QtCore.QRect(220, 60, 113, 27))
        self.skyMapNull.setObjectName(_fromUtf8("skyMapNull"))
        self.skyMapBtn = QtGui.QPushButton(self.tab_4)
        self.skyMapBtn.setGeometry(QtCore.QRect(350, 10, 99, 27))
        self.skyMapBtn.setObjectName(_fromUtf8("skyMapBtn"))
        self.skyMapNullBtn = QtGui.QPushButton(self.tab_4)
        self.skyMapNullBtn.setGeometry(QtCore.QRect(350, 60, 99, 27))
        self.skyMapNullBtn.setObjectName(_fromUtf8("skyMapNullBtn"))
        self.killWorldGen = QtGui.QCheckBox(self.tab_4)
        self.killWorldGen.setGeometry(QtCore.QRect(20, 140, 121, 22))
        self.killWorldGen.setObjectName(_fromUtf8("killWorldGen"))
        self.worldSize = QtGui.QSpinBox(self.tab_4)
        self.worldSize.setGeometry(QtCore.QRect(220, 140, 61, 27))
        self.worldSize.setMaximum(999)
        self.worldSize.setObjectName(_fromUtf8("worldSize"))
        self.label_149 = QtGui.QLabel(self.tab_4)
        self.label_149.setGeometry(QtCore.QRect(290, 140, 71, 31))
        self.label_149.setObjectName(_fromUtf8("label_149"))
        self.fps = QtGui.QSpinBox(self.tab_4)
        self.fps.setGeometry(QtCore.QRect(30, 180, 60, 27))
        self.fps.setMaximum(999)
        self.fps.setObjectName(_fromUtf8("fps"))
        self.label_158 = QtGui.QLabel(self.tab_4)
        self.label_158.setGeometry(QtCore.QRect(90, 180, 71, 31))
        self.label_158.setObjectName(_fromUtf8("label_158"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.pulseMode = QtGui.QCheckBox(self.tab_5)
        self.pulseMode.setGeometry(QtCore.QRect(20, 20, 101, 22))
        self.pulseMode.setObjectName(_fromUtf8("pulseMode"))
        self.packetFrequency = QtGui.QSlider(self.tab_5)
        self.packetFrequency.setGeometry(QtCore.QRect(230, 10, 131, 29))
        self.packetFrequency.setOrientation(QtCore.Qt.Horizontal)
        self.packetFrequency.setObjectName(_fromUtf8("packetFrequency"))
        self.label_10 = QtGui.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(240, 20, 121, 51))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.tab_5)
        self.lcdNumber_2.setGeometry(QtCore.QRect(300, 10, 131, 51))
        self.lcdNumber_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.label_11 = QtGui.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(90, 60, 101, 31))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.odourDensity = QtGui.QDoubleSpinBox(self.tab_5)
        self.odourDensity.setGeometry(QtCore.QRect(20, 60, 62, 27))
        self.odourDensity.setObjectName(_fromUtf8("odourDensity"))
        self.trialNo = QtGui.QSpinBox(self.tab_5)
        self.trialNo.setGeometry(QtCore.QRect(20, 100, 61, 27))
        self.trialNo.setObjectName(_fromUtf8("trialNo"))
        self.label_12 = QtGui.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(90, 100, 101, 31))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_14 = QtGui.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(90, 140, 101, 31))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.captureScale = QtGui.QSpinBox(self.tab_5)
        self.captureScale.setGeometry(QtCore.QRect(20, 140, 61, 27))
        self.captureScale.setObjectName(_fromUtf8("captureScale"))
        self.label_15 = QtGui.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(90, 180, 101, 31))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.captureStart = QtGui.QSpinBox(self.tab_5)
        self.captureStart.setGeometry(QtCore.QRect(20, 180, 61, 27))
        self.captureStart.setObjectName(_fromUtf8("captureStart"))
        self.label_16 = QtGui.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(300, 100, 141, 31))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.playbackIncrement = QtGui.QSpinBox(self.tab_5)
        self.playbackIncrement.setGeometry(QtCore.QRect(230, 100, 61, 27))
        self.playbackIncrement.setObjectName(_fromUtf8("playbackIncrement"))
        self.label_17 = QtGui.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(300, 140, 111, 31))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.recordDur = QtGui.QSpinBox(self.tab_5)
        self.recordDur.setGeometry(QtCore.QRect(230, 140, 61, 27))
        self.recordDur.setObjectName(_fromUtf8("recordDur"))
        self.label_18 = QtGui.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(300, 180, 101, 31))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.recordFps = QtGui.QSpinBox(self.tab_5)
        self.recordFps.setGeometry(QtCore.QRect(230, 180, 61, 27))
        self.recordFps.setObjectName(_fromUtf8("recordFps"))
        self.hcp = QtGui.QCheckBox(self.tab_5)
        self.hcp.setGeometry(QtCore.QRect(20, 220, 101, 22))
        self.hcp.setObjectName(_fromUtf8("hcp"))
        self.quad = QtGui.QCheckBox(self.tab_5)
        self.quad.setGeometry(QtCore.QRect(20, 250, 101, 22))
        self.quad.setObjectName(_fromUtf8("quad"))
        self.posL = QtGui.QLineEdit(self.tab_5)
        self.posL.setGeometry(QtCore.QRect(230, 220, 113, 27))
        self.posL.setObjectName(_fromUtf8("posL"))
        self.label_19 = QtGui.QLabel(self.tab_5)
        self.label_19.setGeometry(QtCore.QRect(350, 220, 101, 21))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.posR = QtGui.QLineEdit(self.tab_5)
        self.posR.setGeometry(QtCore.QRect(230, 260, 113, 27))
        self.posR.setObjectName(_fromUtf8("posR"))
        self.label_20 = QtGui.QLabel(self.tab_5)
        self.label_20.setGeometry(QtCore.QRect(350, 260, 101, 21))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.bboxDist = QtGui.QDoubleSpinBox(self.tab_5)
        self.bboxDist.setGeometry(QtCore.QRect(20, 280, 62, 27))
        self.bboxDist.setObjectName(_fromUtf8("bboxDist"))
        self.label_21 = QtGui.QLabel(self.tab_5)
        self.label_21.setGeometry(QtCore.QRect(90, 280, 101, 31))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(90, 320, 101, 31))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.maxBoutDur = QtGui.QSpinBox(self.tab_5)
        self.maxBoutDur.setGeometry(QtCore.QRect(20, 320, 61, 27))
        self.maxBoutDur.setMaximum(999)
        self.maxBoutDur.setObjectName(_fromUtf8("maxBoutDur"))
        self.modelHeightMap = QtGui.QLineEdit(self.tab_5)
        self.modelHeightMap.setGeometry(QtCore.QRect(20, 390, 113, 27))
        self.modelHeightMap.setText(_fromUtf8(""))
        self.modelHeightMap.setObjectName(_fromUtf8("modelHeightMap"))
        self.label_45 = QtGui.QLabel(self.tab_5)
        self.label_45.setGeometry(QtCore.QRect(150, 360, 121, 31))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.modelSizeSuffix = QtGui.QLineEdit(self.tab_5)
        self.modelSizeSuffix.setGeometry(QtCore.QRect(20, 360, 113, 27))
        self.modelSizeSuffix.setObjectName(_fromUtf8("modelSizeSuffix"))
        self.label_46 = QtGui.QLabel(self.tab_5)
        self.label_46.setGeometry(QtCore.QRect(150, 390, 121, 31))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.modelTextureMapNull = QtGui.QLineEdit(self.tab_5)
        self.modelTextureMapNull.setGeometry(QtCore.QRect(20, 450, 113, 27))
        self.modelTextureMapNull.setText(_fromUtf8(""))
        self.modelTextureMapNull.setObjectName(_fromUtf8("modelTextureMapNull"))
        self.modelTextureMap = QtGui.QLineEdit(self.tab_5)
        self.modelTextureMap.setGeometry(QtCore.QRect(20, 420, 113, 27))
        self.modelTextureMap.setObjectName(_fromUtf8("modelTextureMap"))
        self.label_71 = QtGui.QLabel(self.tab_5)
        self.label_71.setGeometry(QtCore.QRect(150, 420, 131, 31))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.label_72 = QtGui.QLabel(self.tab_5)
        self.label_72.setGeometry(QtCore.QRect(150, 450, 161, 31))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.lrGain = QtGui.QDoubleSpinBox(self.tab_5)
        self.lrGain.setGeometry(QtCore.QRect(530, 30, 62, 27))
        self.lrGain.setObjectName(_fromUtf8("lrGain"))
        self.label_107 = QtGui.QLabel(self.tab_5)
        self.label_107.setGeometry(QtCore.QRect(600, 30, 101, 31))
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.lockFps = QtGui.QCheckBox(self.tab_5)
        self.lockFps.setGeometry(QtCore.QRect(530, 70, 101, 22))
        self.lockFps.setObjectName(_fromUtf8("lockFps"))
        self.label_108 = QtGui.QLabel(self.tab_5)
        self.label_108.setGeometry(QtCore.QRect(540, 100, 191, 31))
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.trajectoryUpdateInterval = QtGui.QSpinBox(self.tab_5)
        self.trajectoryUpdateInterval.setGeometry(QtCore.QRect(460, 100, 61, 27))
        self.trajectoryUpdateInterval.setObjectName(_fromUtf8("trajectoryUpdateInterval"))
        self.label_111 = QtGui.QLabel(self.tab_5)
        self.label_111.setGeometry(QtCore.QRect(540, 130, 91, 31))
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.maxDistance = QtGui.QSpinBox(self.tab_5)
        self.maxDistance.setGeometry(QtCore.QRect(460, 130, 61, 27))
        self.maxDistance.setObjectName(_fromUtf8("maxDistance"))
        self.label_147 = QtGui.QLabel(self.tab_5)
        self.label_147.setGeometry(QtCore.QRect(610, 200, 101, 21))
        self.label_147.setObjectName(_fromUtf8("label_147"))
        self.camFOV = QtGui.QLineEdit(self.tab_5)
        self.camFOV.setGeometry(QtCore.QRect(490, 200, 113, 27))
        self.camFOV.setText(_fromUtf8(""))
        self.camFOV.setObjectName(_fromUtf8("camFOV"))
        self.playerInitPos = QtGui.QLineEdit(self.tab_5)
        self.playerInitPos.setGeometry(QtCore.QRect(490, 240, 113, 27))
        self.playerInitPos.setObjectName(_fromUtf8("playerInitPos"))
        self.label_150 = QtGui.QLabel(self.tab_5)
        self.label_150.setGeometry(QtCore.QRect(620, 240, 101, 31))
        self.label_150.setObjectName(_fromUtf8("label_150"))
        self.label_151 = QtGui.QLabel(self.tab_5)
        self.label_151.setGeometry(QtCore.QRect(560, 280, 101, 31))
        self.label_151.setObjectName(_fromUtf8("label_151"))
        self.playerInitH = QtGui.QSpinBox(self.tab_5)
        self.playerInitH.setGeometry(QtCore.QRect(490, 280, 61, 27))
        self.playerInitH.setMaximum(360)
        self.playerInitH.setObjectName(_fromUtf8("playerInitH"))
        self.label_152 = QtGui.QLabel(self.tab_5)
        self.label_152.setGeometry(QtCore.QRect(560, 320, 101, 31))
        self.label_152.setObjectName(_fromUtf8("label_152"))
        self.windDirection = QtGui.QSpinBox(self.tab_5)
        self.windDirection.setGeometry(QtCore.QRect(490, 320, 61, 27))
        self.windDirection.setMaximum(360)
        self.windDirection.setObjectName(_fromUtf8("windDirection"))
        self.wbad = QtGui.QSpinBox(self.tab_5)
        self.wbad.setGeometry(QtCore.QRect(230, 300, 61, 27))
        self.wbad.setObjectName(_fromUtf8("wbad"))
        self.label_204 = QtGui.QLabel(self.tab_5)
        self.label_204.setGeometry(QtCore.QRect(300, 300, 101, 31))
        self.label_204.setObjectName(_fromUtf8("label_204"))
        self.wbas = QtGui.QSpinBox(self.tab_5)
        self.wbas.setGeometry(QtCore.QRect(230, 330, 61, 27))
        self.wbas.setObjectName(_fromUtf8("wbas"))
        self.label_205 = QtGui.QLabel(self.tab_5)
        self.label_205.setGeometry(QtCore.QRect(300, 330, 101, 31))
        self.label_205.setObjectName(_fromUtf8("label_205"))
        self.bagTrajTopics = QtGui.QLineEdit(self.tab_5)
        self.bagTrajTopics.setGeometry(QtCore.QRect(290, 410, 113, 27))
        self.bagTrajTopics.setObjectName(_fromUtf8("bagTrajTopics"))
        self.bagTrajTopicsBtn = QtGui.QPushButton(self.tab_5)
        self.bagTrajTopicsBtn.setGeometry(QtCore.QRect(420, 410, 99, 27))
        self.bagTrajTopicsBtn.setObjectName(_fromUtf8("bagTrajTopicsBtn"))
        self.bagFullTopics = QtGui.QLineEdit(self.tab_5)
        self.bagFullTopics.setGeometry(QtCore.QRect(290, 370, 113, 27))
        self.bagFullTopics.setObjectName(_fromUtf8("bagFullTopics"))
        self.bagFullTopicsBtn = QtGui.QPushButton(self.tab_5)
        self.bagFullTopicsBtn.setGeometry(QtCore.QRect(420, 370, 99, 27))
        self.bagFullTopicsBtn.setObjectName(_fromUtf8("bagFullTopicsBtn"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_64 = QtGui.QWidget()
        self.tab_64.setObjectName(_fromUtf8("tab_64"))
        self.label_362 = QtGui.QLabel(self.tab_64)
        self.label_362.setGeometry(QtCore.QRect(150, 20, 71, 31))
        self.label_362.setObjectName(_fromUtf8("label_362"))
        self.durList = QtGui.QLineEdit(self.tab_64)
        self.durList.setGeometry(QtCore.QRect(20, 20, 113, 27))
        self.durList.setObjectName(_fromUtf8("durList"))
        self.label_363 = QtGui.QLabel(self.tab_64)
        self.label_363.setGeometry(QtCore.QRect(150, 60, 91, 31))
        self.label_363.setObjectName(_fromUtf8("label_363"))
        self.headingRate = QtGui.QLineEdit(self.tab_64)
        self.headingRate.setGeometry(QtCore.QRect(20, 60, 113, 27))
        self.headingRate.setObjectName(_fromUtf8("headingRate"))
        self.intraTrial = QtGui.QSpinBox(self.tab_64)
        self.intraTrial.setGeometry(QtCore.QRect(20, 100, 61, 27))
        self.intraTrial.setObjectName(_fromUtf8("intraTrial"))
        self.label_364 = QtGui.QLabel(self.tab_64)
        self.label_364.setGeometry(QtCore.QRect(90, 100, 71, 31))
        self.label_364.setObjectName(_fromUtf8("label_364"))
        self.interTrial = QtGui.QSpinBox(self.tab_64)
        self.interTrial.setGeometry(QtCore.QRect(20, 140, 61, 27))
        self.interTrial.setObjectName(_fromUtf8("interTrial"))
        self.label_365 = QtGui.QLabel(self.tab_64)
        self.label_365.setGeometry(QtCore.QRect(90, 140, 71, 31))
        self.label_365.setObjectName(_fromUtf8("label_365"))
        self.startDur = QtGui.QSpinBox(self.tab_64)
        self.startDur.setGeometry(QtCore.QRect(20, 180, 61, 27))
        self.startDur.setObjectName(_fromUtf8("startDur"))
        self.label_366 = QtGui.QLabel(self.tab_64)
        self.label_366.setGeometry(QtCore.QRect(90, 180, 71, 31))
        self.label_366.setObjectName(_fromUtf8("label_366"))
        self.stopDur = QtGui.QSpinBox(self.tab_64)
        self.stopDur.setGeometry(QtCore.QRect(20, 220, 61, 27))
        self.stopDur.setObjectName(_fromUtf8("stopDur"))
        self.label_367 = QtGui.QLabel(self.tab_64)
        self.label_367.setGeometry(QtCore.QRect(90, 220, 71, 31))
        self.label_367.setObjectName(_fromUtf8("label_367"))
        self.stepDur = QtGui.QSpinBox(self.tab_64)
        self.stepDur.setGeometry(QtCore.QRect(20, 260, 61, 27))
        self.stepDur.setMinimum(-99)
        self.stepDur.setObjectName(_fromUtf8("stepDur"))
        self.label_368 = QtGui.QLabel(self.tab_64)
        self.label_368.setGeometry(QtCore.QRect(90, 260, 71, 31))
        self.label_368.setObjectName(_fromUtf8("label_368"))
        self.label_369 = QtGui.QLabel(self.tab_64)
        self.label_369.setGeometry(QtCore.QRect(90, 310, 81, 17))
        self.label_369.setObjectName(_fromUtf8("label_369"))
        self.factorDur = QtGui.QDoubleSpinBox(self.tab_64)
        self.factorDur.setGeometry(QtCore.QRect(20, 300, 62, 27))
        self.factorDur.setObjectName(_fromUtf8("factorDur"))
        self.nSteps = QtGui.QSpinBox(self.tab_64)
        self.nSteps.setGeometry(QtCore.QRect(290, 20, 61, 27))
        self.nSteps.setObjectName(_fromUtf8("nSteps"))
        self.label_370 = QtGui.QLabel(self.tab_64)
        self.label_370.setGeometry(QtCore.QRect(360, 20, 71, 31))
        self.label_370.setObjectName(_fromUtf8("label_370"))
        self.nReps = QtGui.QSpinBox(self.tab_64)
        self.nReps.setGeometry(QtCore.QRect(290, 60, 61, 27))
        self.nReps.setObjectName(_fromUtf8("nReps"))
        self.label_371 = QtGui.QLabel(self.tab_64)
        self.label_371.setGeometry(QtCore.QRect(360, 60, 71, 31))
        self.label_371.setObjectName(_fromUtf8("label_371"))
        self.startHeading = QtGui.QDoubleSpinBox(self.tab_64)
        self.startHeading.setGeometry(QtCore.QRect(290, 100, 62, 27))
        self.startHeading.setDecimals(1)
        self.startHeading.setObjectName(_fromUtf8("startHeading"))
        self.label_372 = QtGui.QLabel(self.tab_64)
        self.label_372.setGeometry(QtCore.QRect(360, 110, 91, 17))
        self.label_372.setObjectName(_fromUtf8("label_372"))
        self.label_373 = QtGui.QLabel(self.tab_64)
        self.label_373.setGeometry(QtCore.QRect(360, 140, 71, 31))
        self.label_373.setObjectName(_fromUtf8("label_373"))
        self.area = QtGui.QSpinBox(self.tab_64)
        self.area.setGeometry(QtCore.QRect(290, 140, 61, 27))
        self.area.setObjectName(_fromUtf8("area"))
        self.stepMode = QtGui.QCheckBox(self.tab_64)
        self.stepMode.setGeometry(QtCore.QRect(520, 70, 99, 22))
        self.stepMode.setObjectName(_fromUtf8("stepMode"))
        self.durListGen = QtGui.QCheckBox(self.tab_64)
        self.durListGen.setGeometry(QtCore.QRect(520, 110, 99, 22))
        self.durListGen.setObjectName(_fromUtf8("durListGen"))
        self.gpMode = QtGui.QCheckBox(self.tab_64)
        self.gpMode.setGeometry(QtCore.QRect(520, 30, 99, 22))
        self.gpMode.setObjectName(_fromUtf8("gpMode"))
        self.areaMode = QtGui.QCheckBox(self.tab_64)
        self.areaMode.setGeometry(QtCore.QRect(520, 190, 141, 22))
        self.areaMode.setObjectName(_fromUtf8("areaMode"))
        self.headingListGen = QtGui.QCheckBox(self.tab_64)
        self.headingListGen.setGeometry(QtCore.QRect(520, 150, 141, 22))
        self.headingListGen.setObjectName(_fromUtf8("headingListGen"))
        self.orderFlip = QtGui.QCheckBox(self.tab_64)
        self.orderFlip.setGeometry(QtCore.QRect(520, 270, 99, 22))
        self.orderFlip.setObjectName(_fromUtf8("orderFlip"))
        self.mouseMode = QtGui.QCheckBox(self.tab_64)
        self.mouseMode.setGeometry(QtCore.QRect(520, 310, 141, 22))
        self.mouseMode.setObjectName(_fromUtf8("mouseMode"))
        self.humanDisplay = QtGui.QCheckBox(self.tab_64)
        self.humanDisplay.setGeometry(QtCore.QRect(520, 350, 141, 22))
        self.humanDisplay.setObjectName(_fromUtf8("humanDisplay"))
        self.signFlip = QtGui.QCheckBox(self.tab_64)
        self.signFlip.setGeometry(QtCore.QRect(520, 230, 99, 22))
        self.signFlip.setObjectName(_fromUtf8("signFlip"))
        self.loadNullModels = QtGui.QCheckBox(self.tab_64)
        self.loadNullModels.setGeometry(QtCore.QRect(520, 380, 131, 22))
        self.loadNullModels.setObjectName(_fromUtf8("loadNullModels"))
        self.tabWidget.addTab(self.tab_64, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.redTexPath = QtGui.QLineEdit(self.tab_7)
        self.redTexPath.setGeometry(QtCore.QRect(30, 100, 113, 27))
        self.redTexPath.setObjectName(_fromUtf8("redTexPath"))
        self.spherePath = QtGui.QLineEdit(self.tab_7)
        self.spherePath.setGeometry(QtCore.QRect(30, 20, 113, 27))
        self.spherePath.setObjectName(_fromUtf8("spherePath"))
        self.greenTexPath = QtGui.QLineEdit(self.tab_7)
        self.greenTexPath.setGeometry(QtCore.QRect(30, 60, 113, 27))
        self.greenTexPath.setObjectName(_fromUtf8("greenTexPath"))
        self.spherePathBtn = QtGui.QPushButton(self.tab_7)
        self.spherePathBtn.setGeometry(QtCore.QRect(160, 20, 111, 27))
        self.spherePathBtn.setObjectName(_fromUtf8("spherePathBtn"))
        self.treePath = QtGui.QLineEdit(self.tab_7)
        self.treePath.setGeometry(QtCore.QRect(30, 140, 113, 27))
        self.treePath.setObjectName(_fromUtf8("treePath"))
        self.greenTexPathBtn = QtGui.QPushButton(self.tab_7)
        self.greenTexPathBtn.setGeometry(QtCore.QRect(160, 60, 111, 27))
        self.greenTexPathBtn.setObjectName(_fromUtf8("greenTexPathBtn"))
        self.redTexPathBtn = QtGui.QPushButton(self.tab_7)
        self.redTexPathBtn.setGeometry(QtCore.QRect(160, 100, 111, 27))
        self.redTexPathBtn.setObjectName(_fromUtf8("redTexPathBtn"))
        self.treePathBtn = QtGui.QPushButton(self.tab_7)
        self.treePathBtn.setGeometry(QtCore.QRect(160, 140, 111, 27))
        self.treePathBtn.setObjectName(_fromUtf8("treePathBtn"))
        self.treeTexPath = QtGui.QLineEdit(self.tab_7)
        self.treeTexPath.setGeometry(QtCore.QRect(30, 180, 113, 27))
        self.treeTexPath.setObjectName(_fromUtf8("treeTexPath"))
        self.treeTexPathBtn = QtGui.QPushButton(self.tab_7)
        self.treeTexPathBtn.setGeometry(QtCore.QRect(160, 180, 111, 27))
        self.treeTexPathBtn.setObjectName(_fromUtf8("treeTexPathBtn"))
        self.heightObjects = QtGui.QSpinBox(self.tab_7)
        self.heightObjects.setGeometry(QtCore.QRect(360, 20, 61, 27))
        self.heightObjects.setObjectName(_fromUtf8("heightObjects"))
        self.label_73 = QtGui.QLabel(self.tab_7)
        self.label_73.setGeometry(QtCore.QRect(440, 16, 101, 31))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.label_74 = QtGui.QLabel(self.tab_7)
        self.label_74.setGeometry(QtCore.QRect(440, 50, 101, 31))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.widthObjects = QtGui.QSpinBox(self.tab_7)
        self.widthObjects.setGeometry(QtCore.QRect(360, 54, 61, 27))
        self.widthObjects.setObjectName(_fromUtf8("widthObjects"))
        self.label_75 = QtGui.QLabel(self.tab_7)
        self.label_75.setGeometry(QtCore.QRect(440, 90, 101, 31))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.lattice = QtGui.QSpinBox(self.tab_7)
        self.lattice.setGeometry(QtCore.QRect(360, 94, 61, 27))
        self.lattice.setObjectName(_fromUtf8("lattice"))
        self.origin = QtGui.QLineEdit(self.tab_7)
        self.origin.setGeometry(QtCore.QRect(360, 130, 113, 27))
        self.origin.setObjectName(_fromUtf8("origin"))
        self.label_76 = QtGui.QLabel(self.tab_7)
        self.label_76.setGeometry(QtCore.QRect(490, 130, 101, 31))
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.treeScale = QtGui.QDoubleSpinBox(self.tab_7)
        self.treeScale.setGeometry(QtCore.QRect(360, 210, 62, 27))
        self.treeScale.setObjectName(_fromUtf8("treeScale"))
        self.sphereScale = QtGui.QDoubleSpinBox(self.tab_7)
        self.sphereScale.setGeometry(QtCore.QRect(360, 170, 62, 27))
        self.sphereScale.setObjectName(_fromUtf8("sphereScale"))
        self.label_109 = QtGui.QLabel(self.tab_7)
        self.label_109.setGeometry(QtCore.QRect(430, 170, 101, 31))
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.label_110 = QtGui.QLabel(self.tab_7)
        self.label_110.setGeometry(QtCore.QRect(430, 210, 101, 31))
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.label_153 = QtGui.QLabel(self.tab_7)
        self.label_153.setGeometry(QtCore.QRect(430, 250, 101, 31))
        self.label_153.setObjectName(_fromUtf8("label_153"))
        self.sphereZ = QtGui.QDoubleSpinBox(self.tab_7)
        self.sphereZ.setGeometry(QtCore.QRect(360, 250, 62, 27))
        self.sphereZ.setObjectName(_fromUtf8("sphereZ"))
        self.label_154 = QtGui.QLabel(self.tab_7)
        self.label_154.setGeometry(QtCore.QRect(430, 290, 101, 31))
        self.label_154.setObjectName(_fromUtf8("label_154"))
        self.treeZ = QtGui.QDoubleSpinBox(self.tab_7)
        self.treeZ.setGeometry(QtCore.QRect(360, 290, 62, 27))
        self.treeZ.setObjectName(_fromUtf8("treeZ"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.DCoffset = QtGui.QDoubleSpinBox(self.tab_3)
        self.DCoffset.setGeometry(QtCore.QRect(30, 14, 71, 27))
        self.DCoffset.setDecimals(3)
        self.DCoffset.setMinimum(-99.99)
        self.DCoffset.setObjectName(_fromUtf8("DCoffset"))
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(110, 10, 68, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(110, 56, 101, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.DCoffsetIncrement = QtGui.QDoubleSpinBox(self.tab_3)
        self.DCoffsetIncrement.setGeometry(QtCore.QRect(30, 60, 71, 27))
        self.DCoffsetIncrement.setDecimals(3)
        self.DCoffsetIncrement.setMinimum(-99.99)
        self.DCoffsetIncrement.setObjectName(_fromUtf8("DCoffsetIncrement"))
        self.frameRecord = QtGui.QCheckBox(self.tab_3)
        self.frameRecord.setGeometry(QtCore.QRect(30, 100, 141, 22))
        self.frameRecord.setObjectName(_fromUtf8("frameRecord"))
        self.gainIncrement = QtGui.QDoubleSpinBox(self.tab_3)
        self.gainIncrement.setGeometry(QtCore.QRect(30, 180, 62, 27))
        self.gainIncrement.setObjectName(_fromUtf8("gainIncrement"))
        self.speedIncrement = QtGui.QDoubleSpinBox(self.tab_3)
        self.speedIncrement.setGeometry(QtCore.QRect(30, 140, 62, 27))
        self.speedIncrement.setObjectName(_fromUtf8("speedIncrement"))
        self.label_157 = QtGui.QLabel(self.tab_3)
        self.label_157.setGeometry(QtCore.QRect(100, 180, 101, 17))
        self.label_157.setObjectName(_fromUtf8("label_157"))
        self.label_156 = QtGui.QLabel(self.tab_3)
        self.label_156.setGeometry(QtCore.QRect(100, 140, 111, 17))
        self.label_156.setObjectName(_fromUtf8("label_156"))
        self.camHpr = QtGui.QLineEdit(self.tab_3)
        self.camHpr.setGeometry(QtCore.QRect(260, 10, 113, 27))
        self.camHpr.setObjectName(_fromUtf8("camHpr"))
        self.label_254 = QtGui.QLabel(self.tab_3)
        self.label_254.setGeometry(QtCore.QRect(390, 10, 101, 31))
        self.label_254.setObjectName(_fromUtf8("label_254"))
        self.label_255 = QtGui.QLabel(self.tab_3)
        self.label_255.setGeometry(QtCore.QRect(340, 46, 101, 31))
        self.label_255.setObjectName(_fromUtf8("label_255"))
        self.frameNum = QtGui.QSpinBox(self.tab_3)
        self.frameNum.setGeometry(QtCore.QRect(260, 50, 61, 27))
        self.frameNum.setObjectName(_fromUtf8("frameNum"))
        self.windowWidth = QtGui.QSpinBox(self.tab_3)
        self.windowWidth.setGeometry(QtCore.QRect(260, 84, 61, 27))
        self.windowWidth.setMaximum(9999)
        self.windowWidth.setObjectName(_fromUtf8("windowWidth"))
        self.label_256 = QtGui.QLabel(self.tab_3)
        self.label_256.setGeometry(QtCore.QRect(340, 80, 101, 31))
        self.label_256.setObjectName(_fromUtf8("label_256"))
        self.windowHeight = QtGui.QSpinBox(self.tab_3)
        self.windowHeight.setGeometry(QtCore.QRect(260, 124, 61, 27))
        self.windowHeight.setMaximum(9999)
        self.windowHeight.setObjectName(_fromUtf8("windowHeight"))
        self.label_257 = QtGui.QLabel(self.tab_3)
        self.label_257.setGeometry(QtCore.QRect(340, 120, 101, 31))
        self.label_257.setObjectName(_fromUtf8("label_257"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(55, 540, 671, 27))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Open|QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.RestoreDefaults|QtGui.QDialogButtonBox.Save|QtGui.QDialogButtonBox.SaveAll)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 745, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QObject.connect(self.gain, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber.display)
        QtCore.QObject.connect(self.packetFrequency, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_2.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.loadWind.setText(_translate("MainWindow", "Wind", None))
        self.loadOdour.setText(_translate("MainWindow", "Odour", None))
        self.loadTrajectory.setText(_translate("MainWindow", "Trajectory", None))
        self.imposeStimulus.setText(_translate("MainWindow", "Impose stimulus", None))
        self.label.setText(_translate("MainWindow", "Loading String", None))
        self.label_2.setText(_translate("MainWindow", "Gain", None))
        self.settingsFile.setText(_translate("MainWindow", "default.json", None))
        self.jsonBtn.setText(_translate("MainWindow", "Na", None))
        self.label_13.setText(_translate("MainWindow", "max speed", None))
        self.disabledFly.setText(_translate("MainWindow", "disable fly", None))
        self.label_155.setText(_translate("MainWindow", "speed", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "General", None))
        self.label_5.setText(_translate("MainWindow", "Fly", None))
        self.label_6.setText(_translate("MainWindow", "Race", None))
        self.label_7.setText(_translate("MainWindow", "Emergence", None))
        self.windQuad.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add <span style=\" font-weight:600;\">4 </span>items</p><p>[0, 0, 0, 0]</p></body></html>", None))
        self.windQuad.setText(_translate("MainWindow", "[]", None))
        self.label_8.setText(_translate("MainWindow", "windQuad", None))
        self.label_9.setText(_translate("MainWindow", "odourQuad", None))
        self.odourQuad.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add <span style=\" font-weight:600;\">4 </span>items</p><p>[0, 0, 0, 0]</p></body></html>", None))
        self.odourQuad.setText(_translate("MainWindow", "[]", None))
        self.odourBtn1.setText(_translate("MainWindow", "Select odour 1", None))
        self.odourBtn2.setText(_translate("MainWindow", "Select odour 2", None))
        self.odourBtn3.setText(_translate("MainWindow", "Select odour 3", None))
        self.odourBtn4.setText(_translate("MainWindow", "Select odour 4", None))
        self.race.setItemText(0, _translate("MainWindow", "apple", None))
        self.race.setItemText(1, _translate("MainWindow", "hawthorn", None))
        self.race.setItemText(2, _translate("MainWindow", "unknown", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Race", None))
        self.generateWorld.setText(_translate("MainWindow", "generate world", None))
        self.loadHUD.setText(_translate("MainWindow", "load HUD", None))
        self.loadWorld.setText(_translate("MainWindow", "load world", None))
        self.replayWorld.setText(_translate("MainWindow", "replay world", None))
        self.skyMapBtn.setText(_translate("MainWindow", "skyMap", None))
        self.skyMapNullBtn.setText(_translate("MainWindow", "skyMapNull", None))
        self.killWorldGen.setText(_translate("MainWindow", "killWorldGen", None))
        self.label_149.setText(_translate("MainWindow", "worldSize", None))
        self.label_158.setText(_translate("MainWindow", "fps", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "World", None))
        self.pulseMode.setText(_translate("MainWindow", "pulseMode", None))
        self.label_10.setText(_translate("MainWindow", "packetFrequency", None))
        self.label_11.setText(_translate("MainWindow", "Odour density", None))
        self.label_12.setText(_translate("MainWindow", "Trial No.", None))
        self.label_14.setText(_translate("MainWindow", "capture scale", None))
        self.label_15.setText(_translate("MainWindow", "capture start", None))
        self.label_16.setText(_translate("MainWindow", "playback increment", None))
        self.label_17.setText(_translate("MainWindow", "record duration", None))
        self.label_18.setText(_translate("MainWindow", "record fps", None))
        self.hcp.setText(_translate("MainWindow", "hcp", None))
        self.quad.setText(_translate("MainWindow", "quad", None))
        self.posL.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add <span style=\" font-weight:600;\">2 </span>items</p><p>(0, 0)</p></body></html>", None))
        self.posL.setText(_translate("MainWindow", "()", None))
        self.label_19.setText(_translate("MainWindow", "posL", None))
        self.posR.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add <span style=\" font-weight:600;\">2 </span>items</p><p>(0, 0)</p></body></html>", None))
        self.posR.setText(_translate("MainWindow", "()", None))
        self.label_20.setText(_translate("MainWindow", "posR", None))
        self.label_21.setText(_translate("MainWindow", "bboxDist", None))
        self.label_22.setText(_translate("MainWindow", "maxBoutDur", None))
        self.label_45.setText(_translate("MainWindow", "modelSizeSuffix", None))
        self.label_46.setText(_translate("MainWindow", "modelHeightMap", None))
        self.label_71.setText(_translate("MainWindow", "modelTextureMap", None))
        self.label_72.setText(_translate("MainWindow", "modelTextureMapNull", None))
        self.label_107.setText(_translate("MainWindow", "lrGain", None))
        self.lockFps.setText(_translate("MainWindow", "lockFps", None))
        self.label_108.setText(_translate("MainWindow", "trajectoryUpdateInterval", None))
        self.label_111.setText(_translate("MainWindow", "maxDistance", None))
        self.label_147.setText(_translate("MainWindow", "camFOV", None))
        self.playerInitPos.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add <span style=\" font-weight:600;\">3 </span>items</p><p>(0, 0, 0)</p></body></html>", None))
        self.playerInitPos.setText(_translate("MainWindow", "()", None))
        self.label_150.setText(_translate("MainWindow", "playerInitPos", None))
        self.label_151.setText(_translate("MainWindow", "playerInitH", None))
        self.label_152.setText(_translate("MainWindow", "windDirection", None))
        self.label_204.setText(_translate("MainWindow", "wbad", None))
        self.label_205.setText(_translate("MainWindow", "wbas", None))
        self.bagTrajTopicsBtn.setText(_translate("MainWindow", "bagTrajTopics", None))
        self.bagFullTopicsBtn.setText(_translate("MainWindow", "bagFullTopics", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Idk", None))
        self.label_362.setText(_translate("MainWindow", "durList", None))
        self.durList.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add <span style=\" font-weight:600;\">4 </span>items</p><p>[0, 0, 0, 0]</p></body></html>", None))
        self.durList.setText(_translate("MainWindow", "[]", None))
        self.label_363.setText(_translate("MainWindow", "headingRate", None))
        self.headingRate.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add <span style=\" font-weight:600;\">4 </span>items</p><p>[0, 0, 0, 0]</p></body></html>", None))
        self.headingRate.setText(_translate("MainWindow", "[]", None))
        self.label_364.setText(_translate("MainWindow", "intraTrial", None))
        self.label_365.setText(_translate("MainWindow", "interTrial", None))
        self.label_366.setText(_translate("MainWindow", "startDur", None))
        self.label_367.setText(_translate("MainWindow", "stopDur", None))
        self.label_368.setText(_translate("MainWindow", "stepDur", None))
        self.label_369.setText(_translate("MainWindow", "factorDur", None))
        self.label_370.setText(_translate("MainWindow", "nSteps", None))
        self.label_371.setText(_translate("MainWindow", "nReps", None))
        self.label_372.setText(_translate("MainWindow", "startHeading", None))
        self.label_373.setText(_translate("MainWindow", "area", None))
        self.stepMode.setText(_translate("MainWindow", "stepMode", None))
        self.durListGen.setText(_translate("MainWindow", "durListGen", None))
        self.gpMode.setText(_translate("MainWindow", "gpMode", None))
        self.areaMode.setText(_translate("MainWindow", "areaMode", None))
        self.headingListGen.setText(_translate("MainWindow", "headingListGen", None))
        self.orderFlip.setText(_translate("MainWindow", "orderFlip", None))
        self.mouseMode.setText(_translate("MainWindow", "mouseMode", None))
        self.humanDisplay.setText(_translate("MainWindow", "humanDisplay", None))
        self.signFlip.setText(_translate("MainWindow", "signFlip", None))
        self.loadNullModels.setText(_translate("MainWindow", "loadNullModels", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_64), _translate("MainWindow", "Idk2", None))
        self.spherePathBtn.setText(_translate("MainWindow", "spherePath", None))
        self.greenTexPathBtn.setText(_translate("MainWindow", "greenTexPath", None))
        self.redTexPathBtn.setText(_translate("MainWindow", "redTexPath", None))
        self.treePathBtn.setText(_translate("MainWindow", "treePath", None))
        self.treeTexPathBtn.setText(_translate("MainWindow", "treeTexPath", None))
        self.label_73.setText(_translate("MainWindow", "heightObjects", None))
        self.label_74.setText(_translate("MainWindow", "widthObjects", None))
        self.label_75.setText(_translate("MainWindow", "lattice", None))
        self.origin.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add <span style=\" font-weight:600;\">3 </span>items</p><p>(0, 0, 0)</p></body></html>", None))
        self.origin.setText(_translate("MainWindow", "()", None))
        self.label_76.setText(_translate("MainWindow", "origin", None))
        self.label_109.setText(_translate("MainWindow", "sphereScale", None))
        self.label_110.setText(_translate("MainWindow", "treeScale", None))
        self.label_153.setText(_translate("MainWindow", "sphereZ", None))
        self.label_154.setText(_translate("MainWindow", "treeZ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Objects", None))
        self.label_3.setText(_translate("MainWindow", "DCoffset", None))
        self.label_4.setText(_translate("MainWindow", "DCoffset Incr.", None))
        self.frameRecord.setText(_translate("MainWindow", "frameRecord", None))
        self.label_157.setText(_translate("MainWindow", "gainIncrement", None))
        self.label_156.setText(_translate("MainWindow", "speedIncrement", None))
        self.camHpr.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add <span style=\" font-weight:600;\">3 </span>items</p><p>(0, 0, 0)</p></body></html>", None))
        self.camHpr.setText(_translate("MainWindow", "()", None))
        self.label_254.setText(_translate("MainWindow", "camHpr", None))
        self.label_255.setText(_translate("MainWindow", "frameNum", None))
        self.label_256.setText(_translate("MainWindow", "windowWidth", None))
        self.label_257.setText(_translate("MainWindow", "windowHeight", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Advanced", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Live", None))

