# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/UnityGui.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RhagGUI(object):
    def setupUi(self, RhagGUI):
        RhagGUI.setObjectName(_fromUtf8("RhagGUI"))
        RhagGUI.resize(809, 1027)
        self.centralwidget = QtGui.QWidget(RhagGUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(9, 9, 811, 991))
        self.frame.setObjectName(_fromUtf8("frame"))
        self.tabWidget = QtGui.QTabWidget(self.frame)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 781, 851))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayout = QtGui.QFormLayout(self.tab)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab)
        self.groupBox_10.setEnabled(True)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_160 = QtGui.QLabel(self.groupBox_10)
        self.label_160.setEnabled(True)
        self.label_160.setObjectName(_fromUtf8("label_160"))
        self.gridLayout_7.addWidget(self.label_160, 4, 4, 1, 1)
        self.mechanicalWindQuad = QtGui.QLineEdit(self.groupBox_10)
        self.mechanicalWindQuad.setEnabled(True)
        self.mechanicalWindQuad.setObjectName(_fromUtf8("mechanicalWindQuad"))
        self.gridLayout_7.addWidget(self.mechanicalWindQuad, 1, 0, 1, 2)
        self.visualWindSpeed = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.visualWindSpeed.setEnabled(True)
        self.visualWindSpeed.setSingleStep(0.05)
        self.visualWindSpeed.setObjectName(_fromUtf8("visualWindSpeed"))
        self.gridLayout_7.addWidget(self.visualWindSpeed, 4, 3, 1, 1)
        self.visualWindQuad = QtGui.QLineEdit(self.groupBox_10)
        self.visualWindQuad.setEnabled(True)
        self.visualWindQuad.setObjectName(_fromUtf8("visualWindQuad"))
        self.gridLayout_7.addWidget(self.visualWindQuad, 1, 3, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_10)
        self.label_31.setEnabled(True)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_7.addWidget(self.label_31, 1, 4, 1, 1)
        self.label_152 = QtGui.QLabel(self.groupBox_10)
        self.label_152.setEnabled(True)
        self.label_152.setObjectName(_fromUtf8("label_152"))
        self.gridLayout_7.addWidget(self.label_152, 4, 2, 1, 1)
        self.loadVisualWind = QtGui.QCheckBox(self.groupBox_10)
        self.loadVisualWind.setEnabled(True)
        self.loadVisualWind.setObjectName(_fromUtf8("loadVisualWind"))
        self.gridLayout_7.addWidget(self.loadVisualWind, 0, 3, 1, 2)
        self.mechanicalWindSpeed = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.mechanicalWindSpeed.setEnabled(True)
        self.mechanicalWindSpeed.setSingleStep(0.05)
        self.mechanicalWindSpeed.setObjectName(_fromUtf8("mechanicalWindSpeed"))
        self.gridLayout_7.addWidget(self.mechanicalWindSpeed, 3, 0, 3, 2)
        self.label_8 = QtGui.QLabel(self.groupBox_10)
        self.label_8.setEnabled(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_7.addWidget(self.label_8, 1, 2, 1, 1)
        self.loadMechanicalWind = QtGui.QCheckBox(self.groupBox_10)
        self.loadMechanicalWind.setEnabled(True)
        self.loadMechanicalWind.setObjectName(_fromUtf8("loadMechanicalWind"))
        self.gridLayout_7.addWidget(self.loadMechanicalWind, 0, 0, 1, 2)
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.groupBox_10)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.maxBoutDur = QtGui.QSpinBox(self.tab)
        self.maxBoutDur.setEnabled(True)
        self.maxBoutDur.setMinimum(-9999)
        self.maxBoutDur.setMaximum(99999)
        self.maxBoutDur.setSingleStep(0)
        self.maxBoutDur.setObjectName(_fromUtf8("maxBoutDur"))
        self.gridLayout_3.addWidget(self.maxBoutDur, 6, 2, 1, 1)
        self.gain = QtGui.QSlider(self.tab)
        self.gain.setEnabled(True)
        self.gain.setMaximum(32)
        self.gain.setProperty("value", 7)
        self.gain.setOrientation(QtCore.Qt.Horizontal)
        self.gain.setObjectName(_fromUtf8("gain"))
        self.gridLayout_3.addWidget(self.gain, 3, 0, 1, 2)
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setEnabled(True)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 4, 3, 1, 1)
        self.lcdGain = QtGui.QLCDNumber(self.tab)
        self.lcdGain.setEnabled(True)
        self.lcdGain.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdGain.setNumDigits(2)
        self.lcdGain.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdGain.setObjectName(_fromUtf8("lcdGain"))
        self.gridLayout_3.addWidget(self.lcdGain, 3, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setEnabled(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 3, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setEnabled(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setEnabled(True)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 4, 1, 1, 1)
        self.loadingString = QtGui.QLineEdit(self.tab)
        self.loadingString.setEnabled(True)
        self.loadingString.setObjectName(_fromUtf8("loadingString"))
        self.gridLayout_3.addWidget(self.loadingString, 1, 0, 1, 1)
        self.emergence = QtGui.QDateEdit(self.tab)
        self.emergence.setDate(QtCore.QDate(2020, 1, 1))
        self.emergence.setCalendarPopup(True)
        self.emergence.setObjectName(_fromUtf8("emergence"))
        self.gridLayout_3.addWidget(self.emergence, 11, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 11, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setEnabled(True)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 6, 3, 1, 1)
        self.race = QtGui.QComboBox(self.tab)
        self.race.setObjectName(_fromUtf8("race"))
        self.race.addItem(_fromUtf8(""))
        self.race.addItem(_fromUtf8(""))
        self.race.addItem(_fromUtf8(""))
        self.race.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.race, 11, 0, 1, 1)
        self.posL = QtGui.QLineEdit(self.tab)
        self.posL.setEnabled(True)
        self.posL.setObjectName(_fromUtf8("posL"))
        self.gridLayout_3.addWidget(self.posL, 4, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setEnabled(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 6, 1, 1, 1)
        self.label_50 = QtGui.QLabel(self.tab)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_3.addWidget(self.label_50, 10, 3, 1, 1)
        self.posR = QtGui.QLineEdit(self.tab)
        self.posR.setEnabled(True)
        self.posR.setObjectName(_fromUtf8("posR"))
        self.gridLayout_3.addWidget(self.posR, 4, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 11, 3, 1, 1)
        self.maxSpeed = QtGui.QDoubleSpinBox(self.tab)
        self.maxSpeed.setEnabled(True)
        self.maxSpeed.setObjectName(_fromUtf8("maxSpeed"))
        self.gridLayout_3.addWidget(self.maxSpeed, 6, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 7, 1, 1, 1)
        self.DCoffset = QtGui.QDoubleSpinBox(self.tab)
        self.DCoffset.setEnabled(True)
        self.DCoffset.setDecimals(3)
        self.DCoffset.setMinimum(-99.99)
        self.DCoffset.setObjectName(_fromUtf8("DCoffset"))
        self.gridLayout_3.addWidget(self.DCoffset, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 3, 2, 1, 1)
        self.fly = QtGui.QLineEdit(self.tab)
        self.fly.setObjectName(_fromUtf8("fly"))
        self.gridLayout_3.addWidget(self.fly, 10, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.tab)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_3.addWidget(self.label_49, 10, 1, 1, 1)
        self.metaExpData = QtGui.QLineEdit(self.tab)
        self.metaExpData.setObjectName(_fromUtf8("metaExpData"))
        self.gridLayout_3.addWidget(self.metaExpData, 10, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 7, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 8, 1, 1, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.SpanningRole, self.gridLayout_3)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setEnabled(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_364 = QtGui.QLabel(self.groupBox)
        self.label_364.setEnabled(True)
        self.label_364.setObjectName(_fromUtf8("label_364"))
        self.gridLayout_4.addWidget(self.label_364, 2, 2, 1, 2)
        self.imposeStimulusDuration = QtGui.QDoubleSpinBox(self.groupBox)
        self.imposeStimulusDuration.setEnabled(True)
        self.imposeStimulusDuration.setObjectName(_fromUtf8("imposeStimulusDuration"))
        self.gridLayout_4.addWidget(self.imposeStimulusDuration, 2, 1, 1, 1)
        self.imposeStimulus = QtGui.QCheckBox(self.groupBox)
        self.imposeStimulus.setEnabled(True)
        self.imposeStimulus.setObjectName(_fromUtf8("imposeStimulus"))
        self.gridLayout_4.addWidget(self.imposeStimulus, 0, 1, 1, 1)
        self.signFlip = QtGui.QCheckBox(self.groupBox)
        self.signFlip.setEnabled(True)
        self.signFlip.setObjectName(_fromUtf8("signFlip"))
        self.gridLayout_4.addWidget(self.signFlip, 0, 2, 1, 1)
        self.label_371 = QtGui.QLabel(self.groupBox)
        self.label_371.setEnabled(True)
        self.label_371.setObjectName(_fromUtf8("label_371"))
        self.gridLayout_4.addWidget(self.label_371, 2, 7, 1, 1)
        self.nReps = QtGui.QSpinBox(self.groupBox)
        self.nReps.setEnabled(True)
        self.nReps.setMinimum(1)
        self.nReps.setObjectName(_fromUtf8("nReps"))
        self.gridLayout_4.addWidget(self.nReps, 2, 6, 1, 1)
        self.orderFlip = QtGui.QCheckBox(self.groupBox)
        self.orderFlip.setEnabled(True)
        self.orderFlip.setObjectName(_fromUtf8("orderFlip"))
        self.gridLayout_4.addWidget(self.orderFlip, 0, 6, 1, 1)
        self.label_363 = QtGui.QLabel(self.groupBox)
        self.label_363.setEnabled(True)
        self.label_363.setObjectName(_fromUtf8("label_363"))
        self.gridLayout_4.addWidget(self.label_363, 1, 7, 1, 1)
        self.headingRate = QtGui.QLineEdit(self.groupBox)
        self.headingRate.setEnabled(True)
        self.headingRate.setObjectName(_fromUtf8("headingRate"))
        self.gridLayout_4.addWidget(self.headingRate, 1, 1, 1, 6)
        self.label_364.raise_()
        self.imposeStimulusDuration.raise_()
        self.headingRate.raise_()
        self.imposeStimulus.raise_()
        self.signFlip.raise_()
        self.label_371.raise_()
        self.nReps.raise_()
        self.orderFlip.raise_()
        self.label_363.raise_()
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.groupBox)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setGeometry(QtCore.QRect(-10, 0, 511, 641))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.obj1Scale_2 = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.obj1Scale_2.setEnabled(True)
        self.obj1Scale_2.setObjectName(_fromUtf8("obj1Scale_2"))
        self.gridLayout.addWidget(self.obj1Scale_2, 8, 0, 1, 1)
        self.label_158 = QtGui.QLabel(self.groupBox_4)
        self.label_158.setEnabled(True)
        self.label_158.setObjectName(_fromUtf8("label_158"))
        self.gridLayout.addWidget(self.label_158, 1, 3, 1, 1)
        self.obj2PathBtn_2 = QtGui.QPushButton(self.groupBox_4)
        self.obj2PathBtn_2.setEnabled(True)
        self.obj2PathBtn_2.setObjectName(_fromUtf8("obj2PathBtn_2"))
        self.gridLayout.addWidget(self.obj2PathBtn_2, 7, 3, 1, 1)
        self.minWbas = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.minWbas.setEnabled(True)
        self.minWbas.setDecimals(3)
        self.minWbas.setMinimum(-99.99)
        self.minWbas.setObjectName(_fromUtf8("minWbas"))
        self.gridLayout.addWidget(self.minWbas, 2, 0, 1, 1)
        self.camHpr = QtGui.QLineEdit(self.groupBox_4)
        self.camHpr.setEnabled(True)
        self.camHpr.setObjectName(_fromUtf8("camHpr"))
        self.gridLayout.addWidget(self.camHpr, 1, 0, 1, 1)
        self.playerInitH = QtGui.QSpinBox(self.groupBox_4)
        self.playerInitH.setEnabled(True)
        self.playerInitH.setMaximum(360)
        self.playerInitH.setObjectName(_fromUtf8("playerInitH"))
        self.gridLayout.addWidget(self.playerInitH, 0, 2, 1, 1)
        self.minFlightSpeed = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.minFlightSpeed.setEnabled(True)
        self.minFlightSpeed.setDecimals(3)
        self.minFlightSpeed.setMinimum(-99.99)
        self.minFlightSpeed.setObjectName(_fromUtf8("minFlightSpeed"))
        self.gridLayout.addWidget(self.minFlightSpeed, 2, 2, 1, 1)
        self.label_156 = QtGui.QLabel(self.groupBox_4)
        self.label_156.setEnabled(True)
        self.label_156.setObjectName(_fromUtf8("label_156"))
        self.gridLayout.addWidget(self.label_156, 9, 3, 1, 1)
        self.object1_2 = QtGui.QLineEdit(self.groupBox_4)
        self.object1_2.setEnabled(True)
        self.object1_2.setObjectName(_fromUtf8("object1_2"))
        self.gridLayout.addWidget(self.object1_2, 6, 0, 1, 3)
        self.playerInitPos = QtGui.QLineEdit(self.groupBox_4)
        self.playerInitPos.setEnabled(True)
        self.playerInitPos.setObjectName(_fromUtf8("playerInitPos"))
        self.gridLayout.addWidget(self.playerInitPos, 0, 0, 1, 1)
        self.maxWbas_2 = QtGui.QLabel(self.groupBox_4)
        self.maxWbas_2.setEnabled(True)
        self.maxWbas_2.setObjectName(_fromUtf8("maxWbas_2"))
        self.gridLayout.addWidget(self.maxWbas_2, 3, 1, 1, 1)
        self.label_155 = QtGui.QLabel(self.groupBox_4)
        self.label_155.setEnabled(True)
        self.label_155.setObjectName(_fromUtf8("label_155"))
        self.gridLayout.addWidget(self.label_155, 8, 3, 1, 1)
        self.obj2Scale_2 = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.obj2Scale_2.setEnabled(True)
        self.obj2Scale_2.setObjectName(_fromUtf8("obj2Scale_2"))
        self.gridLayout.addWidget(self.obj2Scale_2, 9, 0, 1, 1)
        self.obj1Z_2 = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.obj1Z_2.setEnabled(True)
        self.obj1Z_2.setMinimum(-100.0)
        self.obj1Z_2.setObjectName(_fromUtf8("obj1Z_2"))
        self.gridLayout.addWidget(self.obj1Z_2, 8, 2, 1, 1)
        self.obj2Z_2 = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.obj2Z_2.setEnabled(True)
        self.obj2Z_2.setMinimum(-99.99)
        self.obj2Z_2.setObjectName(_fromUtf8("obj2Z_2"))
        self.gridLayout.addWidget(self.obj2Z_2, 9, 2, 1, 1)
        self.label_254 = QtGui.QLabel(self.groupBox_4)
        self.label_254.setEnabled(True)
        self.label_254.setObjectName(_fromUtf8("label_254"))
        self.gridLayout.addWidget(self.label_254, 1, 1, 1, 1)
        self.maxFlightSpeed = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.maxFlightSpeed.setEnabled(True)
        self.maxFlightSpeed.setDecimals(3)
        self.maxFlightSpeed.setMinimum(-99.99)
        self.maxFlightSpeed.setObjectName(_fromUtf8("maxFlightSpeed"))
        self.gridLayout.addWidget(self.maxFlightSpeed, 3, 2, 1, 1)
        self.minWbas_2 = QtGui.QLabel(self.groupBox_4)
        self.minWbas_2.setEnabled(True)
        self.minWbas_2.setObjectName(_fromUtf8("minWbas_2"))
        self.gridLayout.addWidget(self.minWbas_2, 2, 1, 1, 1)
        self.minSpeed_2 = QtGui.QLabel(self.groupBox_4)
        self.minSpeed_2.setEnabled(True)
        self.minSpeed_2.setObjectName(_fromUtf8("minSpeed_2"))
        self.gridLayout.addWidget(self.minSpeed_2, 2, 3, 1, 1)
        self.label_112 = QtGui.QLabel(self.groupBox_4)
        self.label_112.setEnabled(True)
        self.label_112.setObjectName(_fromUtf8("label_112"))
        self.gridLayout.addWidget(self.label_112, 8, 1, 1, 1)
        self.object2_2 = QtGui.QLineEdit(self.groupBox_4)
        self.object2_2.setEnabled(True)
        self.object2_2.setObjectName(_fromUtf8("object2_2"))
        self.gridLayout.addWidget(self.object2_2, 7, 0, 1, 3)
        self.label_151 = QtGui.QLabel(self.groupBox_4)
        self.label_151.setEnabled(True)
        self.label_151.setObjectName(_fromUtf8("label_151"))
        self.gridLayout.addWidget(self.label_151, 0, 3, 1, 1)
        self.maxWbas = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.maxWbas.setEnabled(True)
        self.maxWbas.setDecimals(3)
        self.maxWbas.setMinimum(-99.99)
        self.maxWbas.setObjectName(_fromUtf8("maxWbas"))
        self.gridLayout.addWidget(self.maxWbas, 3, 0, 1, 1)
        self.label_111 = QtGui.QLabel(self.groupBox_4)
        self.label_111.setEnabled(True)
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.gridLayout.addWidget(self.label_111, 9, 1, 1, 1)
        self.fps = QtGui.QSpinBox(self.groupBox_4)
        self.fps.setEnabled(True)
        self.fps.setMaximum(999)
        self.fps.setObjectName(_fromUtf8("fps"))
        self.gridLayout.addWidget(self.fps, 1, 2, 1, 1)
        self.obj1PathBtn_2 = QtGui.QPushButton(self.groupBox_4)
        self.obj1PathBtn_2.setEnabled(True)
        self.obj1PathBtn_2.setObjectName(_fromUtf8("obj1PathBtn_2"))
        self.gridLayout.addWidget(self.obj1PathBtn_2, 6, 3, 1, 1)
        self.maxSpeed_3 = QtGui.QLabel(self.groupBox_4)
        self.maxSpeed_3.setEnabled(True)
        self.maxSpeed_3.setObjectName(_fromUtf8("maxSpeed_3"))
        self.gridLayout.addWidget(self.maxSpeed_3, 3, 3, 1, 1)
        self.label_150 = QtGui.QLabel(self.groupBox_4)
        self.label_150.setEnabled(True)
        self.label_150.setObjectName(_fromUtf8("label_150"))
        self.gridLayout.addWidget(self.label_150, 0, 1, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_9.setEnabled(True)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_47 = QtGui.QLabel(self.groupBox_9)
        self.label_47.setEnabled(True)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_16.addWidget(self.label_47, 0, 1, 1, 1)
        self.bagTrajTopics = QtGui.QLineEdit(self.groupBox_9)
        self.bagTrajTopics.setEnabled(True)
        self.bagTrajTopics.setObjectName(_fromUtf8("bagTrajTopics"))
        self.gridLayout_16.addWidget(self.bagTrajTopics, 1, 0, 1, 1)
        self.bagFullTopics = QtGui.QLineEdit(self.groupBox_9)
        self.bagFullTopics.setEnabled(True)
        self.bagFullTopics.setObjectName(_fromUtf8("bagFullTopics"))
        self.gridLayout_16.addWidget(self.bagFullTopics, 0, 0, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBox_9)
        self.label_48.setEnabled(True)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_16.addWidget(self.label_48, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_9, 10, 0, 1, 4)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(220, 50, 164, 63))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 34, 471, 57))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.replayPath = QtGui.QLineEdit(self.layoutWidget)
        self.replayPath.setEnabled(True)
        self.replayPath.setObjectName(_fromUtf8("replayPath"))
        self.gridLayout_2.addWidget(self.replayPath, 1, 0, 1, 1)
        self.replayPathBtn = QtGui.QPushButton(self.layoutWidget)
        self.replayPathBtn.setEnabled(True)
        self.replayPathBtn.setObjectName(_fromUtf8("replayPathBtn"))
        self.gridLayout_2.addWidget(self.replayPathBtn, 1, 1, 1, 1)
        self.replayWorld = QtGui.QCheckBox(self.layoutWidget)
        self.replayWorld.setEnabled(True)
        self.replayWorld.setObjectName(_fromUtf8("replayWorld"))
        self.gridLayout_2.addWidget(self.replayWorld, 0, 0, 1, 1)
        self.layoutWidget.raise_()
        self.groupBox_2.raise_()
        self.gridLayout.addWidget(self.groupBox_3, 11, 0, 1, 4)
        self.autoThrottle = QtGui.QCheckBox(self.groupBox_4)
        self.autoThrottle.setEnabled(True)
        self.autoThrottle.setObjectName(_fromUtf8("autoThrottle"))
        self.gridLayout.addWidget(self.autoThrottle, 4, 0, 1, 1)
        self.closedLoopDur = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.closedLoopDur.setEnabled(True)
        self.closedLoopDur.setDecimals(1)
        self.closedLoopDur.setMinimum(0.0)
        self.closedLoopDur.setProperty("value", 1.0)
        self.closedLoopDur.setObjectName(_fromUtf8("closedLoopDur"))
        self.gridLayout.addWidget(self.closedLoopDur, 5, 2, 1, 1)
        self.closedLoopDur_label = QtGui.QLabel(self.groupBox_4)
        self.closedLoopDur_label.setEnabled(True)
        self.closedLoopDur_label.setToolTip(_fromUtf8(""))
        self.closedLoopDur_label.setObjectName(_fromUtf8("closedLoopDur_label"))
        self.gridLayout.addWidget(self.closedLoopDur_label, 5, 3, 1, 1)
        self.openLoopDur = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.openLoopDur.setEnabled(True)
        self.openLoopDur.setDecimals(1)
        self.openLoopDur.setMinimum(0.0)
        self.openLoopDur.setProperty("value", 1.0)
        self.openLoopDur.setObjectName(_fromUtf8("openLoopDur"))
        self.gridLayout.addWidget(self.openLoopDur, 4, 2, 1, 1)
        self.openLoopDur_label = QtGui.QLabel(self.groupBox_4)
        self.openLoopDur_label.setEnabled(True)
        self.openLoopDur_label.setMouseTracking(True)
        self.openLoopDur_label.setToolTip(_fromUtf8(""))
        self.openLoopDur_label.setObjectName(_fromUtf8("openLoopDur_label"))
        self.gridLayout.addWidget(self.openLoopDur_label, 4, 3, 1, 1)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_6)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 9, 1051, 871))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.pausePlot = QtGui.QCheckBox(self.tab_2)
        self.pausePlot.setGeometry(QtCore.QRect(200, 750, 71, 22))
        self.pausePlot.setObjectName(_fromUtf8("pausePlot"))
        self.clearPlot = QtGui.QPushButton(self.tab_2)
        self.clearPlot.setGeometry(QtCore.QRect(109, 748, 85, 27))
        self.clearPlot.setAutoDefault(False)
        self.clearPlot.setDefault(False)
        self.clearPlot.setObjectName(_fromUtf8("clearPlot"))
        self.resetView = QtGui.QPushButton(self.tab_2)
        self.resetView.setGeometry(QtCore.QRect(8, 748, 95, 27))
        self.resetView.setObjectName(_fromUtf8("resetView"))
        self.livePosition = QtGui.QLabel(self.tab_2)
        self.livePosition.setGeometry(QtCore.QRect(290, 540, 121, 81))
        self.livePosition.setObjectName(_fromUtf8("livePosition"))
        self.positionLabel = QtGui.QLabel(self.tab_2)
        self.positionLabel.setGeometry(QtCore.QRect(280, 520, 121, 21))
        self.positionLabel.setObjectName(_fromUtf8("positionLabel"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(610, 750, 121, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lcdServoAngle = QtGui.QLCDNumber(self.tab_2)
        self.lcdServoAngle.setGeometry(QtCore.QRect(320, 660, 71, 61))
        self.lcdServoAngle.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdServoAngle.setNumDigits(3)
        self.lcdServoAngle.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdServoAngle.setObjectName(_fromUtf8("lcdServoAngle"))
        self.label_23 = QtGui.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(330, 710, 121, 31))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.compassServo = QwtCompass(self.tab_2)
        self.compassServo.setGeometry(QtCore.QRect(357, 520, 340, 240))
        self.compassServo.setProperty("readOnly", True)
        self.compassServo.setProperty("lineWidth", 4)
        self.compassServo.setObjectName(_fromUtf8("compassServo"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 530, 261, 201))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.histog = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.histog.setMargin(0)
        self.histog.setObjectName(_fromUtf8("histog"))
        self.lcdHeadingAngle = QtGui.QLCDNumber(self.tab_2)
        self.lcdHeadingAngle.setGeometry(QtCore.QRect(620, 710, 111, 41))
        self.lcdHeadingAngle.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdHeadingAngle.setNumDigits(3)
        self.lcdHeadingAngle.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdHeadingAngle.setObjectName(_fromUtf8("lcdHeadingAngle"))
        self.compassHeading = QwtCompass(self.tab_2)
        self.compassHeading.setGeometry(QtCore.QRect(446, 540, 160, 191))
        self.compassHeading.setProperty("readOnly", True)
        self.compassHeading.setProperty("lineWidth", 4)
        self.compassHeading.setObjectName(_fromUtf8("compassHeading"))
        self.stateLabel = QtGui.QLabel(self.tab_2)
        self.stateLabel.setGeometry(QtCore.QRect(580, 0, 121, 21))
        self.stateLabel.setObjectName(_fromUtf8("stateLabel"))
        self.liveState = QtGui.QLabel(self.tab_2)
        self.liveState.setGeometry(QtCore.QRect(550, 0, 171, 461))
        self.liveState.setObjectName(_fromUtf8("liveState"))
        self.compassSlip = QwtCompass(self.tab_2)
        self.compassSlip.setGeometry(QtCore.QRect(480, 575, 91, 121))
        self.compassSlip.setProperty("readOnly", True)
        self.compassSlip.setProperty("lineWidth", 4)
        self.compassSlip.setObjectName(_fromUtf8("compassSlip"))
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(640, 490, 121, 31))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.lcdSlipAngle = QtGui.QLCDNumber(self.tab_2)
        self.lcdSlipAngle.setGeometry(QtCore.QRect(640, 510, 71, 61))
        self.lcdSlipAngle.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdSlipAngle.setNumDigits(3)
        self.lcdSlipAngle.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdSlipAngle.setObjectName(_fromUtf8("lcdSlipAngle"))
        self.positionLabel_2 = QtGui.QLabel(self.tab_2)
        self.positionLabel_2.setGeometry(QtCore.QRect(450, 660, 61, 21))
        self.positionLabel_2.setObjectName(_fromUtf8("positionLabel_2"))
        self.positionLabel_3 = QtGui.QLabel(self.tab_2)
        self.positionLabel_3.setGeometry(QtCore.QRect(490, 640, 61, 21))
        self.positionLabel_3.setObjectName(_fromUtf8("positionLabel_3"))
        self.positionLabel_4 = QtGui.QLabel(self.tab_2)
        self.positionLabel_4.setGeometry(QtCore.QRect(420, 680, 61, 21))
        self.positionLabel_4.setObjectName(_fromUtf8("positionLabel_4"))
        self.trackFly = QtGui.QCheckBox(self.tab_2)
        self.trackFly.setGeometry(QtCore.QRect(540, 470, 111, 22))
        self.trackFly.setObjectName(_fromUtf8("trackFly"))
        self.label_33 = QtGui.QLabel(self.tab_2)
        self.label_33.setGeometry(QtCore.QRect(540, 440, 81, 29))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalSlider = QtGui.QSlider(self.tab_2)
        self.verticalSlider.setGeometry(QtCore.QRect(500, 30, 61, 421))
        self.verticalSlider.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.verticalSlider.setMinimum(-60)
        self.verticalSlider.setMaximum(40)
        self.verticalSlider.setSingleStep(2)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(False)
        self.verticalSlider.setInvertedControls(False)
        self.verticalSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 511, 491))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.trajectoryLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.trajectoryLayout.setMargin(0)
        self.trajectoryLayout.setObjectName(_fromUtf8("trajectoryLayout"))
        self.livePosition.raise_()
        self.pausePlot.raise_()
        self.clearPlot.raise_()
        self.resetView.raise_()
        self.positionLabel.raise_()
        self.label_5.raise_()
        self.label_23.raise_()
        self.gridLayoutWidget_2.raise_()
        self.lcdHeadingAngle.raise_()
        self.lcdServoAngle.raise_()
        self.compassServo.raise_()
        self.compassHeading.raise_()
        self.stateLabel.raise_()
        self.liveState.raise_()
        self.compassSlip.raise_()
        self.label_32.raise_()
        self.lcdSlipAngle.raise_()
        self.positionLabel_2.raise_()
        self.positionLabel_3.raise_()
        self.positionLabel_4.raise_()
        self.trackFly.raise_()
        self.label_33.raise_()
        self.verticalSlider.raise_()
        self.gridLayoutWidget.raise_()
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_8)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 30, 701, 591))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.replayTrajectoryLayout = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.replayTrajectoryLayout.setMargin(0)
        self.replayTrajectoryLayout.setObjectName(_fromUtf8("replayTrajectoryLayout"))
        self.compassServo_2 = QwtCompass(self.tab_8)
        self.compassServo_2.setGeometry(QtCore.QRect(690, 460, 340, 240))
        self.compassServo_2.setProperty("readOnly", True)
        self.compassServo_2.setProperty("lineWidth", 4)
        self.compassServo_2.setObjectName(_fromUtf8("compassServo_2"))
        self.clearPlot_2 = QtGui.QPushButton(self.tab_8)
        self.clearPlot_2.setGeometry(QtCore.QRect(90, 700, 85, 27))
        self.clearPlot_2.setAutoDefault(False)
        self.clearPlot_2.setDefault(False)
        self.clearPlot_2.setObjectName(_fromUtf8("clearPlot_2"))
        self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.groupBox_5 = QtGui.QGroupBox(self.frame)
        self.groupBox_5.setEnabled(True)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 850, 781, 129))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.camParamBtn = QtGui.QPushButton(self.groupBox_5)
        self.camParamBtn.setEnabled(True)
        self.camParamBtn.setObjectName(_fromUtf8("camParamBtn"))
        self.gridLayout_5.addWidget(self.camParamBtn, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.groupBox_5)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Open|QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.RestoreDefaults|QtGui.QDialogButtonBox.Save|QtGui.QDialogButtonBox.SaveAll)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_5.addWidget(self.buttonBox, 0, 1, 1, 1)
        self.rqtBtn = QtGui.QPushButton(self.groupBox_5)
        self.rqtBtn.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rqtBtn.sizePolicy().hasHeightForWidth())
        self.rqtBtn.setSizePolicy(sizePolicy)
        self.rqtBtn.setObjectName(_fromUtf8("rqtBtn"))
        self.gridLayout_5.addWidget(self.rqtBtn, 1, 0, 1, 1)
        self.stopVRBtn = QtGui.QPushButton(self.groupBox_5)
        self.stopVRBtn.setEnabled(True)
        self.stopVRBtn.setObjectName(_fromUtf8("stopVRBtn"))
        self.gridLayout_5.addWidget(self.stopVRBtn, 1, 1, 1, 1)
        self.wbadBtn = QtGui.QPushButton(self.groupBox_5)
        self.wbadBtn.setEnabled(True)
        self.wbadBtn.setObjectName(_fromUtf8("wbadBtn"))
        self.gridLayout_5.addWidget(self.wbadBtn, 2, 0, 1, 1)
        self.startVRBtn = QtGui.QPushButton(self.groupBox_5)
        self.startVRBtn.setEnabled(True)
        self.startVRBtn.setDefault(True)
        self.startVRBtn.setObjectName(_fromUtf8("startVRBtn"))
        self.gridLayout_5.addWidget(self.startVRBtn, 2, 1, 1, 1)
        RhagGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RhagGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        RhagGUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(RhagGUI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        RhagGUI.setStatusBar(self.statusbar)

        self.retranslateUi(RhagGUI)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RhagGUI)

    def retranslateUi(self, RhagGUI):
        RhagGUI.setWindowTitle(_translate("RhagGUI", "MainWindow", None))
        self.groupBox_10.setTitle(_translate("RhagGUI", "Control Wind", None))
        self.label_160.setText(_translate("RhagGUI", "Visual Wind Speed", None))
        self.mechanicalWindQuad.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">4 </span>items</p><p>[0, 0, 0, 0]</p></body></html>", None))
        self.mechanicalWindQuad.setText(_translate("RhagGUI", "[]", None))
        self.visualWindQuad.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">4 </span>items</p><p>[0, 0, 0, 0]</p></body></html>", None))
        self.visualWindQuad.setText(_translate("RhagGUI", "[]", None))
        self.label_31.setText(_translate("RhagGUI", "Visual Wind Quad", None))
        self.label_152.setText(_translate("RhagGUI", "Mechanical Wind Speed", None))
        self.loadVisualWind.setText(_translate("RhagGUI", "Visual Wind", None))
        self.label_8.setText(_translate("RhagGUI", "Mechanical Wind Quad", None))
        self.loadMechanicalWind.setText(_translate("RhagGUI", "Mechanical Wind", None))
        self.label_20.setText(_translate("RhagGUI", "posR", None))
        self.label_3.setText(_translate("RhagGUI", "DCoffset", None))
        self.label.setText(_translate("RhagGUI", "Loading String", None))
        self.label_19.setText(_translate("RhagGUI", "posL", None))
        self.label_6.setText(_translate("RhagGUI", "Race", None))
        self.label_22.setText(_translate("RhagGUI", "maxBoutDur", None))
        self.race.setItemText(0, _translate("RhagGUI", "drosophila", None))
        self.race.setItemText(1, _translate("RhagGUI", "apple", None))
        self.race.setItemText(2, _translate("RhagGUI", "hawthorn", None))
        self.race.setItemText(3, _translate("RhagGUI", "unknown", None))
        self.posL.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">2 </span>items</p><p>(0, 0)</p></body></html>", None))
        self.posL.setText(_translate("RhagGUI", "()", None))
        self.label_13.setText(_translate("RhagGUI", "max speed", None))
        self.label_50.setText(_translate("RhagGUI", "metaExpData", None))
        self.posR.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">2 </span>items</p><p>(0, 0)</p></body></html>", None))
        self.posR.setText(_translate("RhagGUI", "()", None))
        self.label_7.setText(_translate("RhagGUI", "Emergence", None))
        self.label_2.setText(_translate("RhagGUI", "Gain", None))
        self.label_49.setText(_translate("RhagGUI", "fly", None))
        self.groupBox.setTitle(_translate("RhagGUI", "Impose parameters", None))
        self.label_364.setText(_translate("RhagGUI", "Stimulus duration", None))
        self.imposeStimulus.setText(_translate("RhagGUI", "Impose stimulus", None))
        self.signFlip.setText(_translate("RhagGUI", "signFlip", None))
        self.label_371.setText(_translate("RhagGUI", "nReps", None))
        self.orderFlip.setText(_translate("RhagGUI", "orderFlip", None))
        self.label_363.setText(_translate("RhagGUI", "headingRate", None))
        self.headingRate.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">x </span>items</p><p>[]</p></body></html>", None))
        self.headingRate.setText(_translate("RhagGUI", "[]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("RhagGUI", "General", None))
        self.groupBox_4.setTitle(_translate("RhagGUI", "GroupBox", None))
        self.label_158.setText(_translate("RhagGUI", "fps", None))
        self.obj2PathBtn_2.setText(_translate("RhagGUI", "object 2", None))
        self.camHpr.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">3 </span>items</p><p>(0, 0, 0)</p></body></html>", None))
        self.camHpr.setText(_translate("RhagGUI", "()", None))
        self.label_156.setText(_translate("RhagGUI", "obj2Z", None))
        self.playerInitPos.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">3 </span>items</p><p>(0, 0, 0)</p></body></html>", None))
        self.playerInitPos.setText(_translate("RhagGUI", "()", None))
        self.maxWbas_2.setText(_translate("RhagGUI", "maxWbas", None))
        self.label_155.setText(_translate("RhagGUI", "obj1Z", None))
        self.label_254.setText(_translate("RhagGUI", "camphr", None))
        self.minWbas_2.setText(_translate("RhagGUI", "minWbas", None))
        self.minSpeed_2.setText(_translate("RhagGUI", "minFlightSpeed", None))
        self.label_112.setText(_translate("RhagGUI", "obj1Scale", None))
        self.label_151.setText(_translate("RhagGUI", "playerInitH", None))
        self.label_111.setText(_translate("RhagGUI", "obj2Scale", None))
        self.obj1PathBtn_2.setText(_translate("RhagGUI", "object 1", None))
        self.maxSpeed_3.setText(_translate("RhagGUI", "maxFlightSpeed", None))
        self.label_150.setText(_translate("RhagGUI", "playerInitPos", None))
        self.groupBox_9.setTitle(_translate("RhagGUI", "Bag Record ", None))
        self.label_47.setText(_translate("RhagGUI", "bagFullTopics", None))
        self.label_48.setText(_translate("RhagGUI", "bagTrajTopics", None))
        self.groupBox_3.setTitle(_translate("RhagGUI", "Replay ", None))
        self.replayPathBtn.setText(_translate("RhagGUI", "Select replay bag", None))
        self.replayWorld.setText(_translate("RhagGUI", "replay world", None))
        self.autoThrottle.setText(_translate("RhagGUI", "autoThrottle", None))
        self.closedLoopDur_label.setText(_translate("RhagGUI", "closedLoopDur", None))
        self.openLoopDur_label.setText(_translate("RhagGUI", "openLoopDur", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("RhagGUI", "World", None))
        self.pausePlot.setText(_translate("RhagGUI", "Pause", None))
        self.clearPlot.setText(_translate("RhagGUI", "Clear Plot", None))
        self.resetView.setText(_translate("RhagGUI", "Reset View", None))
        self.livePosition.setText(_translate("RhagGUI", "None", None))
        self.positionLabel.setText(_translate("RhagGUI", "Position", None))
        self.label_5.setText(_translate("RhagGUI", "Heading Angle", None))
        self.label_23.setText(_translate("RhagGUI", "Servo Angle", None))
        self.stateLabel.setText(_translate("RhagGUI", "State", None))
        self.liveState.setText(_translate("RhagGUI", "None", None))
        self.label_32.setText(_translate("RhagGUI", "Slip Angle", None))
        self.positionLabel_2.setText(_translate("RhagGUI", "Heading", None))
        self.positionLabel_3.setText(_translate("RhagGUI", "Slip", None))
        self.positionLabel_4.setText(_translate("RhagGUI", "Servo", None))
        self.trackFly.setText(_translate("RhagGUI", "Track Fly", None))
        self.label_33.setText(_translate("RhagGUI", "Track Width", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("RhagGUI", "Tab 1", None))
        self.clearPlot_2.setText(_translate("RhagGUI", "Clear Plot", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("RhagGUI", "Page", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("RhagGUI", "Live", None))
        self.camParamBtn.setText(_translate("RhagGUI", "Camera Parameters", None))
        self.rqtBtn.setText(_translate("RhagGUI", "RQT plot", None))
        self.stopVRBtn.setText(_translate("RhagGUI", "STOP VR", None))
        self.wbadBtn.setText(_translate("RhagGUI", "Wing Beat Analyser", None))
from PyQt4.Qwt5.Qwt import QwtCompass, QwtDial; from pyqtgraph import PlotWidget;
