# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/makeGUI.ui'
#
# Created: Sat Aug 26 00:24:45 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RhagGUI(object):
    def setupUi(self, RhagGUI):
        RhagGUI.setObjectName(_fromUtf8("RhagGUI"))
        RhagGUI.resize(741, 1052)
        self.centralwidget = QtGui.QWidget(RhagGUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.camParamBtn = QtGui.QPushButton(self.centralwidget)
        self.camParamBtn.setObjectName(_fromUtf8("camParamBtn"))
        self.gridLayout_9.addWidget(self.camParamBtn, 3, 0, 1, 1)
        self.startVRBtn = QtGui.QPushButton(self.centralwidget)
        self.startVRBtn.setDefault(True)
        self.startVRBtn.setObjectName(_fromUtf8("startVRBtn"))
        self.gridLayout_9.addWidget(self.startVRBtn, 4, 1, 1, 1)
        self.stopVRBtn = QtGui.QPushButton(self.centralwidget)
        self.stopVRBtn.setObjectName(_fromUtf8("stopVRBtn"))
        self.gridLayout_9.addWidget(self.stopVRBtn, 4, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Open|QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.RestoreDefaults|QtGui.QDialogButtonBox.Save|QtGui.QDialogButtonBox.SaveAll)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_9.addWidget(self.buttonBox, 1, 0, 1, 2)
        self.wbadBtn = QtGui.QPushButton(self.centralwidget)
        self.wbadBtn.setObjectName(_fromUtf8("wbadBtn"))
        self.gridLayout_9.addWidget(self.wbadBtn, 3, 1, 1, 1)
        self.rqtBtn = QtGui.QPushButton(self.centralwidget)
        self.rqtBtn.setObjectName(_fromUtf8("rqtBtn"))
        self.gridLayout_9.addWidget(self.rqtBtn, 2, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gain = QtGui.QSlider(self.tab)
        self.gain.setMaximum(25)
        self.gain.setProperty("value", 7)
        self.gain.setOrientation(QtCore.Qt.Horizontal)
        self.gain.setObjectName(_fromUtf8("gain"))
        self.gridLayout_6.addWidget(self.gain, 2, 1, 1, 1)
        self.maxSpeed = QtGui.QDoubleSpinBox(self.tab)
        self.maxSpeed.setObjectName(_fromUtf8("maxSpeed"))
        self.gridLayout_6.addWidget(self.maxSpeed, 2, 5, 1, 1)
        self.loadOdour = QtGui.QCheckBox(self.tab)
        self.loadOdour.setObjectName(_fromUtf8("loadOdour"))
        self.gridLayout_6.addWidget(self.loadOdour, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 2, 2, 1, 1)
        self.loadWind = QtGui.QCheckBox(self.tab)
        self.loadWind.setObjectName(_fromUtf8("loadWind"))
        self.gridLayout_6.addWidget(self.loadWind, 2, 0, 1, 1)
        self.loadingString = QtGui.QLineEdit(self.tab)
        self.loadingString.setObjectName(_fromUtf8("loadingString"))
        self.gridLayout_6.addWidget(self.loadingString, 0, 1, 2, 1)
        self.loadTrajectory = QtGui.QCheckBox(self.tab)
        self.loadTrajectory.setObjectName(_fromUtf8("loadTrajectory"))
        self.gridLayout_6.addWidget(self.loadTrajectory, 3, 0, 1, 1)
        self.lcdGain = QtGui.QLCDNumber(self.tab)
        self.lcdGain.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdGain.setNumDigits(2)
        self.lcdGain.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdGain.setObjectName(_fromUtf8("lcdGain"))
        self.gridLayout_6.addWidget(self.lcdGain, 2, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 2, 6, 1, 1)
        self.tabWidget1 = QtGui.QTabWidget(self.tab)
        self.tabWidget1.setEnabled(True)
        self.tabWidget1.setObjectName(_fromUtf8("tabWidget1"))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.groupBox_3 = QtGui.QGroupBox(self.tabWidgetPage1)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(-1, 9, 681, 421))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.odour1 = QtGui.QLineEdit(self.groupBox_3)
        self.odour1.setObjectName(_fromUtf8("odour1"))
        self.gridLayout_5.addWidget(self.odour1, 2, 2, 1, 1)
        self.odour4 = QtGui.QLineEdit(self.groupBox_3)
        self.odour4.setObjectName(_fromUtf8("odour4"))
        self.gridLayout_5.addWidget(self.odour4, 3, 2, 1, 1)
        self.odourBtn1 = QtGui.QPushButton(self.groupBox_3)
        self.odourBtn1.setObjectName(_fromUtf8("odourBtn1"))
        self.gridLayout_5.addWidget(self.odourBtn1, 2, 3, 1, 1)
        self.odour2 = QtGui.QLineEdit(self.groupBox_3)
        self.odour2.setObjectName(_fromUtf8("odour2"))
        self.gridLayout_5.addWidget(self.odour2, 2, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_6.setEnabled(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.odour3Mask = QtGui.QLineEdit(self.groupBox_6)
        self.odour3Mask.setGeometry(QtCore.QRect(17, 48, 137, 22))
        self.odour3Mask.setObjectName(_fromUtf8("odour3Mask"))
        self.odour3MaskBtn = QtGui.QPushButton(self.groupBox_6)
        self.odour3MaskBtn.setGeometry(QtCore.QRect(160, 48, 153, 22))
        self.odour3MaskBtn.setObjectName(_fromUtf8("odour3MaskBtn"))
        self.odour4Mask = QtGui.QLineEdit(self.groupBox_6)
        self.odour4Mask.setGeometry(QtCore.QRect(319, 48, 129, 22))
        self.odour4Mask.setObjectName(_fromUtf8("odour4Mask"))
        self.odour2Mask = QtGui.QLineEdit(self.groupBox_6)
        self.odour2Mask.setGeometry(QtCore.QRect(17, 20, 137, 22))
        self.odour2Mask.setObjectName(_fromUtf8("odour2Mask"))
        self.odour1Mask = QtGui.QLineEdit(self.groupBox_6)
        self.odour1Mask.setGeometry(QtCore.QRect(319, 20, 129, 22))
        self.odour1Mask.setObjectName(_fromUtf8("odour1Mask"))
        self.odour1MaskBtn = QtGui.QPushButton(self.groupBox_6)
        self.odour1MaskBtn.setGeometry(QtCore.QRect(454, 20, 153, 22))
        self.odour1MaskBtn.setObjectName(_fromUtf8("odour1MaskBtn"))
        self.odour4MaskBtn = QtGui.QPushButton(self.groupBox_6)
        self.odour4MaskBtn.setGeometry(QtCore.QRect(454, 48, 153, 22))
        self.odour4MaskBtn.setObjectName(_fromUtf8("odour4MaskBtn"))
        self.odour2MaskBtn = QtGui.QPushButton(self.groupBox_6)
        self.odour2MaskBtn.setGeometry(QtCore.QRect(160, 20, 153, 22))
        self.odour2MaskBtn.setObjectName(_fromUtf8("odour2MaskBtn"))
        self.gridLayout_5.addWidget(self.groupBox_6, 6, 0, 1, 4)
        self.odourBtn2 = QtGui.QPushButton(self.groupBox_3)
        self.odourBtn2.setObjectName(_fromUtf8("odourBtn2"))
        self.gridLayout_5.addWidget(self.odourBtn2, 2, 1, 1, 1)
        self.plotOdourQuad = QtGui.QCheckBox(self.groupBox_3)
        self.plotOdourQuad.setObjectName(_fromUtf8("plotOdourQuad"))
        self.gridLayout_5.addWidget(self.plotOdourQuad, 0, 0, 1, 1)
        self.packetDur = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.packetDur.setAccelerated(True)
        self.packetDur.setDecimals(3)
        self.packetDur.setMaximum(10.0)
        self.packetDur.setSingleStep(0.01)
        self.packetDur.setObjectName(_fromUtf8("packetDur"))
        self.gridLayout_5.addWidget(self.packetDur, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 1, 1, 1, 1)
        self.odourBtn4 = QtGui.QPushButton(self.groupBox_3)
        self.odourBtn4.setObjectName(_fromUtf8("odourBtn4"))
        self.gridLayout_5.addWidget(self.odourBtn4, 3, 3, 1, 1)
        self.odourBtn3 = QtGui.QPushButton(self.groupBox_3)
        self.odourBtn3.setObjectName(_fromUtf8("odourBtn3"))
        self.gridLayout_5.addWidget(self.odourBtn3, 3, 1, 1, 1)
        self.odour3 = QtGui.QLineEdit(self.groupBox_3)
        self.odour3.setObjectName(_fromUtf8("odour3"))
        self.gridLayout_5.addWidget(self.odour3, 3, 0, 1, 1)
        self.odourQuad = QtGui.QLineEdit(self.groupBox_3)
        self.odourQuad.setObjectName(_fromUtf8("odourQuad"))
        self.gridLayout_5.addWidget(self.odourQuad, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 1, 3, 1, 1)
        self.useOdourMask = QtGui.QCheckBox(self.groupBox_3)
        self.useOdourMask.setEnabled(True)
        self.useOdourMask.setObjectName(_fromUtf8("useOdourMask"))
        self.gridLayout_5.addWidget(self.useOdourMask, 5, 0, 1, 1)
        self.beepPathBtn = QtGui.QPushButton(self.groupBox_3)
        self.beepPathBtn.setObjectName(_fromUtf8("beepPathBtn"))
        self.gridLayout_5.addWidget(self.beepPathBtn, 4, 3, 1, 1)
        self.beepPath = QtGui.QLineEdit(self.groupBox_3)
        self.beepPath.setObjectName(_fromUtf8("beepPath"))
        self.gridLayout_5.addWidget(self.beepPath, 4, 0, 1, 3)
        self.useValve1 = QtGui.QCheckBox(self.groupBox_3)
        self.useValve1.setObjectName(_fromUtf8("useValve1"))
        self.gridLayout_5.addWidget(self.useValve1, 0, 1, 1, 1)
        self.useValve2 = QtGui.QCheckBox(self.groupBox_3)
        self.useValve2.setObjectName(_fromUtf8("useValve2"))
        self.gridLayout_5.addWidget(self.useValve2, 0, 2, 1, 1)
        self.tabWidget1.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_11.setTitle(_fromUtf8(""))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_159 = QtGui.QLabel(self.groupBox_11)
        self.label_159.setObjectName(_fromUtf8("label_159"))
        self.gridLayout_12.addWidget(self.label_159, 6, 2, 1, 1)
        self.label_160 = QtGui.QLabel(self.groupBox_11)
        self.label_160.setObjectName(_fromUtf8("label_160"))
        self.gridLayout_12.addWidget(self.label_160, 9, 2, 1, 1)
        self.pfStimDur_2 = QtGui.QLabel(self.groupBox_11)
        self.pfStimDur_2.setObjectName(_fromUtf8("pfStimDur_2"))
        self.gridLayout_12.addWidget(self.pfStimDur_2, 3, 2, 1, 1)
        self.pfPreStimDur = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.pfPreStimDur.setMaximum(999.0)
        self.pfPreStimDur.setProperty("value", 5.0)
        self.pfPreStimDur.setObjectName(_fromUtf8("pfPreStimDur"))
        self.gridLayout_12.addWidget(self.pfPreStimDur, 2, 0, 1, 1)
        self.pfNReps = QtGui.QSpinBox(self.groupBox_11)
        self.pfNReps.setMaximum(999)
        self.pfNReps.setObjectName(_fromUtf8("pfNReps"))
        self.gridLayout_12.addWidget(self.pfNReps, 6, 0, 1, 1)
        self.pfStimDur = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.pfStimDur.setMaximum(9999.0)
        self.pfStimDur.setProperty("value", 5.0)
        self.pfStimDur.setObjectName(_fromUtf8("pfStimDur"))
        self.gridLayout_12.addWidget(self.pfStimDur, 3, 0, 1, 1)
        self.pfPostStimDur = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.pfPostStimDur.setMaximum(999.0)
        self.pfPostStimDur.setProperty("value", 5.0)
        self.pfPostStimDur.setObjectName(_fromUtf8("pfPostStimDur"))
        self.gridLayout_12.addWidget(self.pfPostStimDur, 5, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_11)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_12.addWidget(self.label_28, 2, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_11)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_12.addWidget(self.label_27, 1, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_11)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_12.addWidget(self.label_30, 5, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_11)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_12.addWidget(self.label_29, 4, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_11)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_12.addWidget(self.label_26, 0, 2, 1, 1)
        self.pfPreStim = QtGui.QSpinBox(self.groupBox_11)
        self.pfPreStim.setMaximum(999)
        self.pfPreStim.setObjectName(_fromUtf8("pfPreStim"))
        self.gridLayout_12.addWidget(self.pfPreStim, 1, 0, 1, 1)
        self.pfMode = QtGui.QComboBox(self.groupBox_11)
        self.pfMode.setObjectName(_fromUtf8("pfMode"))
        self.pfMode.addItem(_fromUtf8(""))
        self.pfMode.addItem(_fromUtf8(""))
        self.gridLayout_12.addWidget(self.pfMode, 9, 0, 1, 1)
        self.pfPostStim = QtGui.QSpinBox(self.groupBox_11)
        self.pfPostStim.setMaximum(999)
        self.pfPostStim.setObjectName(_fromUtf8("pfPostStim"))
        self.gridLayout_12.addWidget(self.pfPostStim, 4, 0, 1, 1)
        self.pfStimList = QtGui.QLineEdit(self.groupBox_11)
        self.pfStimList.setObjectName(_fromUtf8("pfStimList"))
        self.gridLayout_12.addWidget(self.pfStimList, 0, 0, 1, 2)
        self.pfGenTimeSeries = QtGui.QCheckBox(self.groupBox_11)
        self.pfGenTimeSeries.setChecked(True)
        self.pfGenTimeSeries.setObjectName(_fromUtf8("pfGenTimeSeries"))
        self.gridLayout_12.addWidget(self.pfGenTimeSeries, 10, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_11, 0, 0, 1, 1)
        self.tabWidget1.addTab(self.tab_5, _fromUtf8(""))
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName(_fromUtf8("tabWidgetPage2"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tabWidgetPage2)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.groupBox_5 = QtGui.QGroupBox(self.tabWidgetPage2)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_10.setEnabled(False)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 0, 267, 129))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.windQuad = QtGui.QLineEdit(self.groupBox_10)
        self.windQuad.setEnabled(False)
        self.windQuad.setObjectName(_fromUtf8("windQuad"))
        self.gridLayout_7.addWidget(self.windQuad, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_10)
        self.label_8.setEnabled(False)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_7.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_152 = QtGui.QLabel(self.groupBox_10)
        self.label_152.setEnabled(False)
        self.label_152.setObjectName(_fromUtf8("label_152"))
        self.gridLayout_7.addWidget(self.label_152, 1, 1, 1, 1)
        self.windQuadOpen = QtGui.QLineEdit(self.groupBox_10)
        self.windQuadOpen.setEnabled(False)
        self.windQuadOpen.setObjectName(_fromUtf8("windQuadOpen"))
        self.gridLayout_7.addWidget(self.windQuadOpen, 2, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_10)
        self.label_31.setEnabled(False)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_7.addWidget(self.label_31, 2, 1, 1, 1)
        self.windSpeed = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.windSpeed.setEnabled(False)
        self.windSpeed.setSingleStep(0.05)
        self.windSpeed.setObjectName(_fromUtf8("windSpeed"))
        self.gridLayout_7.addWidget(self.windSpeed, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.tabWidget1.addTab(self.tabWidgetPage2, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.tabWidget1, 8, 0, 1, 7)
        self.fps = QtGui.QSpinBox(self.tab)
        self.fps.setMaximum(999)
        self.fps.setObjectName(_fromUtf8("fps"))
        self.gridLayout_6.addWidget(self.fps, 0, 5, 2, 1)
        self.label_158 = QtGui.QLabel(self.tab)
        self.label_158.setObjectName(_fromUtf8("label_158"))
        self.gridLayout_6.addWidget(self.label_158, 0, 6, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.tabWidget_4 = QtGui.QTabWidget(self.tab_7)
        self.tabWidget_4.setEnabled(True)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 40, 691, 431))
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_11)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 10, 249, 393))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.DCoffset = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.DCoffset.setDecimals(3)
        self.DCoffset.setMinimum(-99.99)
        self.DCoffset.setObjectName(_fromUtf8("DCoffset"))
        self.gridLayout_3.addWidget(self.DCoffset, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.maxBoutDur = QtGui.QSpinBox(self.groupBox_4)
        self.maxBoutDur.setMinimum(-9999)
        self.maxBoutDur.setMaximum(99999)
        self.maxBoutDur.setSingleStep(0)
        self.maxBoutDur.setObjectName(_fromUtf8("maxBoutDur"))
        self.gridLayout_3.addWidget(self.maxBoutDur, 1, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 1, 1, 1, 1)
        self.maxDistance = QtGui.QSpinBox(self.groupBox_4)
        self.maxDistance.setMaximum(9999)
        self.maxDistance.setObjectName(_fromUtf8("maxDistance"))
        self.gridLayout_3.addWidget(self.maxDistance, 2, 0, 1, 1)
        self.label_111 = QtGui.QLabel(self.groupBox_4)
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.gridLayout_3.addWidget(self.label_111, 2, 1, 1, 1)
        self.playerInitPos = QtGui.QLineEdit(self.groupBox_4)
        self.playerInitPos.setObjectName(_fromUtf8("playerInitPos"))
        self.gridLayout_3.addWidget(self.playerInitPos, 3, 0, 1, 1)
        self.label_150 = QtGui.QLabel(self.groupBox_4)
        self.label_150.setObjectName(_fromUtf8("label_150"))
        self.gridLayout_3.addWidget(self.label_150, 3, 1, 1, 1)
        self.playerInitH = QtGui.QSpinBox(self.groupBox_4)
        self.playerInitH.setMaximum(360)
        self.playerInitH.setObjectName(_fromUtf8("playerInitH"))
        self.gridLayout_3.addWidget(self.playerInitH, 4, 0, 1, 1)
        self.label_151 = QtGui.QLabel(self.groupBox_4)
        self.label_151.setObjectName(_fromUtf8("label_151"))
        self.gridLayout_3.addWidget(self.label_151, 4, 1, 1, 1)
        self.camFOV = QtGui.QLineEdit(self.groupBox_4)
        self.camFOV.setObjectName(_fromUtf8("camFOV"))
        self.gridLayout_3.addWidget(self.camFOV, 5, 0, 1, 1)
        self.label_147 = QtGui.QLabel(self.groupBox_4)
        self.label_147.setObjectName(_fromUtf8("label_147"))
        self.gridLayout_3.addWidget(self.label_147, 5, 1, 1, 1)
        self.camHpr = QtGui.QLineEdit(self.groupBox_4)
        self.camHpr.setObjectName(_fromUtf8("camHpr"))
        self.gridLayout_3.addWidget(self.camHpr, 6, 0, 1, 1)
        self.label_254 = QtGui.QLabel(self.groupBox_4)
        self.label_254.setObjectName(_fromUtf8("label_254"))
        self.gridLayout_3.addWidget(self.label_254, 6, 1, 1, 1)
        self.minWbas = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.minWbas.setDecimals(3)
        self.minWbas.setMinimum(-99.99)
        self.minWbas.setObjectName(_fromUtf8("minWbas"))
        self.gridLayout_3.addWidget(self.minWbas, 7, 0, 1, 1)
        self.minWbas_2 = QtGui.QLabel(self.groupBox_4)
        self.minWbas_2.setObjectName(_fromUtf8("minWbas_2"))
        self.gridLayout_3.addWidget(self.minWbas_2, 7, 1, 1, 1)
        self.maxWbas = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.maxWbas.setDecimals(3)
        self.maxWbas.setMinimum(-99.99)
        self.maxWbas.setObjectName(_fromUtf8("maxWbas"))
        self.gridLayout_3.addWidget(self.maxWbas, 8, 0, 1, 1)
        self.maxWbas_2 = QtGui.QLabel(self.groupBox_4)
        self.maxWbas_2.setObjectName(_fromUtf8("maxWbas_2"))
        self.gridLayout_3.addWidget(self.maxWbas_2, 8, 1, 1, 1)
        self.minFlightSpeed = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.minFlightSpeed.setDecimals(3)
        self.minFlightSpeed.setMinimum(-99.99)
        self.minFlightSpeed.setObjectName(_fromUtf8("minFlightSpeed"))
        self.gridLayout_3.addWidget(self.minFlightSpeed, 9, 0, 1, 1)
        self.minSpeed_2 = QtGui.QLabel(self.groupBox_4)
        self.minSpeed_2.setObjectName(_fromUtf8("minSpeed_2"))
        self.gridLayout_3.addWidget(self.minSpeed_2, 9, 1, 1, 1)
        self.maxFlightSpeed = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.maxFlightSpeed.setDecimals(3)
        self.maxFlightSpeed.setMinimum(-99.99)
        self.maxFlightSpeed.setObjectName(_fromUtf8("maxFlightSpeed"))
        self.gridLayout_3.addWidget(self.maxFlightSpeed, 10, 0, 1, 1)
        self.maxSpeed_3 = QtGui.QLabel(self.groupBox_4)
        self.maxSpeed_3.setObjectName(_fromUtf8("maxSpeed_3"))
        self.gridLayout_3.addWidget(self.maxSpeed_3, 10, 1, 1, 1)
        self.tabWidget_4.addTab(self.tab_11, _fromUtf8(""))
        self.tabWidget_4Page1 = QtGui.QWidget()
        self.tabWidget_4Page1.setObjectName(_fromUtf8("tabWidget_4Page1"))
        self.groupBox_7 = QtGui.QGroupBox(self.tabWidget_4Page1)
        self.groupBox_7.setEnabled(True)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 661, 360))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.obj2Scale = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.obj2Scale.setObjectName(_fromUtf8("obj2Scale"))
        self.gridLayout_8.addWidget(self.obj2Scale, 1, 2, 1, 1)
        self.randPos = QtGui.QCheckBox(self.groupBox_7)
        self.randPos.setObjectName(_fromUtf8("randPos"))
        self.gridLayout_8.addWidget(self.randPos, 2, 4, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_7)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_8.addWidget(self.label_19, 10, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_7)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_8.addWidget(self.label_10, 10, 5, 1, 1)
        self.treeTexPathBtn = QtGui.QPushButton(self.groupBox_7)
        self.treeTexPathBtn.setObjectName(_fromUtf8("treeTexPathBtn"))
        self.gridLayout_8.addWidget(self.treeTexPathBtn, 11, 1, 1, 1)
        self.redTexPathBtn = QtGui.QPushButton(self.groupBox_7)
        self.redTexPathBtn.setObjectName(_fromUtf8("redTexPathBtn"))
        self.gridLayout_8.addWidget(self.redTexPathBtn, 10, 1, 1, 1)
        self.greenTexPath = QtGui.QLineEdit(self.groupBox_7)
        self.greenTexPath.setObjectName(_fromUtf8("greenTexPath"))
        self.gridLayout_8.addWidget(self.greenTexPath, 13, 0, 1, 1)
        self.label_110 = QtGui.QLabel(self.groupBox_7)
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.gridLayout_8.addWidget(self.label_110, 1, 3, 1, 1)
        self.skyMap = QtGui.QLineEdit(self.groupBox_7)
        self.skyMap.setObjectName(_fromUtf8("skyMap"))
        self.gridLayout_8.addWidget(self.skyMap, 4, 0, 1, 1)
        self.label_109 = QtGui.QLabel(self.groupBox_7)
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.gridLayout_8.addWidget(self.label_109, 0, 3, 1, 1)
        self.object1 = QtGui.QLineEdit(self.groupBox_7)
        self.object1.setObjectName(_fromUtf8("object1"))
        self.gridLayout_8.addWidget(self.object1, 0, 0, 1, 1)
        self.obj1Scale = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.obj1Scale.setObjectName(_fromUtf8("obj1Scale"))
        self.gridLayout_8.addWidget(self.obj1Scale, 0, 2, 1, 1)
        self.obj1PathBtn = QtGui.QPushButton(self.groupBox_7)
        self.obj1PathBtn.setObjectName(_fromUtf8("obj1PathBtn"))
        self.gridLayout_8.addWidget(self.obj1PathBtn, 0, 1, 1, 1)
        self.object2 = QtGui.QLineEdit(self.groupBox_7)
        self.object2.setObjectName(_fromUtf8("object2"))
        self.gridLayout_8.addWidget(self.object2, 1, 0, 1, 1)
        self.obj2PathBtn = QtGui.QPushButton(self.groupBox_7)
        self.obj2PathBtn.setObjectName(_fromUtf8("obj2PathBtn"))
        self.gridLayout_8.addWidget(self.obj2PathBtn, 1, 1, 1, 1)
        self.posR = QtGui.QLineEdit(self.groupBox_7)
        self.posR.setObjectName(_fromUtf8("posR"))
        self.gridLayout_8.addWidget(self.posR, 11, 2, 1, 1)
        self.obj2Z = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.obj2Z.setMinimum(-99.99)
        self.obj2Z.setObjectName(_fromUtf8("obj2Z"))
        self.gridLayout_8.addWidget(self.obj2Z, 1, 4, 1, 1)
        self.obj1Z = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.obj1Z.setMinimum(-100.0)
        self.obj1Z.setObjectName(_fromUtf8("obj1Z"))
        self.gridLayout_8.addWidget(self.obj1Z, 0, 4, 1, 1)
        self.label_153 = QtGui.QLabel(self.groupBox_7)
        self.label_153.setObjectName(_fromUtf8("label_153"))
        self.gridLayout_8.addWidget(self.label_153, 0, 5, 1, 1)
        self.label_149 = QtGui.QLabel(self.groupBox_7)
        self.label_149.setObjectName(_fromUtf8("label_149"))
        self.gridLayout_8.addWidget(self.label_149, 2, 3, 1, 1)
        self.label_154 = QtGui.QLabel(self.groupBox_7)
        self.label_154.setObjectName(_fromUtf8("label_154"))
        self.gridLayout_8.addWidget(self.label_154, 1, 5, 1, 1)
        self.worldSize = QtGui.QSpinBox(self.groupBox_7)
        self.worldSize.setMaximum(9999)
        self.worldSize.setObjectName(_fromUtf8("worldSize"))
        self.gridLayout_8.addWidget(self.worldSize, 2, 2, 1, 1)
        self.modelTextureMap = QtGui.QLineEdit(self.groupBox_7)
        self.modelTextureMap.setObjectName(_fromUtf8("modelTextureMap"))
        self.gridLayout_8.addWidget(self.modelTextureMap, 2, 0, 1, 1)
        self.modelTextureMapBtn = QtGui.QPushButton(self.groupBox_7)
        self.modelTextureMapBtn.setObjectName(_fromUtf8("modelTextureMapBtn"))
        self.gridLayout_8.addWidget(self.modelTextureMapBtn, 2, 1, 1, 1)
        self.skyMapBtn = QtGui.QPushButton(self.groupBox_7)
        self.skyMapBtn.setObjectName(_fromUtf8("skyMapBtn"))
        self.gridLayout_8.addWidget(self.skyMapBtn, 4, 1, 1, 1)
        self.modelTextureMapNull = QtGui.QLineEdit(self.groupBox_7)
        self.modelTextureMapNull.setText(_fromUtf8(""))
        self.modelTextureMapNull.setObjectName(_fromUtf8("modelTextureMapNull"))
        self.gridLayout_8.addWidget(self.modelTextureMapNull, 5, 0, 1, 1)
        self.modelHeightMap = QtGui.QLineEdit(self.groupBox_7)
        self.modelHeightMap.setText(_fromUtf8(""))
        self.modelHeightMap.setObjectName(_fromUtf8("modelHeightMap"))
        self.gridLayout_8.addWidget(self.modelHeightMap, 14, 0, 1, 1)
        self.skyMapNull = QtGui.QLineEdit(self.groupBox_7)
        self.skyMapNull.setObjectName(_fromUtf8("skyMapNull"))
        self.gridLayout_8.addWidget(self.skyMapNull, 6, 0, 1, 1)
        self.treeTexPath = QtGui.QLineEdit(self.groupBox_7)
        self.treeTexPath.setObjectName(_fromUtf8("treeTexPath"))
        self.gridLayout_8.addWidget(self.treeTexPath, 11, 0, 1, 1)
        self.modelHeightMapBtn = QtGui.QPushButton(self.groupBox_7)
        self.modelHeightMapBtn.setObjectName(_fromUtf8("modelHeightMapBtn"))
        self.gridLayout_8.addWidget(self.modelHeightMapBtn, 14, 1, 1, 1)
        self.greenTexPathBtn = QtGui.QPushButton(self.groupBox_7)
        self.greenTexPathBtn.setObjectName(_fromUtf8("greenTexPathBtn"))
        self.gridLayout_8.addWidget(self.greenTexPathBtn, 13, 1, 1, 1)
        self.modelTextureMapNullBtn = QtGui.QPushButton(self.groupBox_7)
        self.modelTextureMapNullBtn.setObjectName(_fromUtf8("modelTextureMapNullBtn"))
        self.gridLayout_8.addWidget(self.modelTextureMapNullBtn, 5, 1, 1, 1)
        self.redTexPath = QtGui.QLineEdit(self.groupBox_7)
        self.redTexPath.setObjectName(_fromUtf8("redTexPath"))
        self.gridLayout_8.addWidget(self.redTexPath, 10, 0, 1, 1)
        self.skyMapNullBtn = QtGui.QPushButton(self.groupBox_7)
        self.skyMapNullBtn.setObjectName(_fromUtf8("skyMapNullBtn"))
        self.gridLayout_8.addWidget(self.skyMapNullBtn, 6, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_7)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_8.addWidget(self.label_21, 5, 3, 1, 1)
        self.bboxDist = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.bboxDist.setObjectName(_fromUtf8("bboxDist"))
        self.gridLayout_8.addWidget(self.bboxDist, 5, 2, 1, 1)
        self.label_76 = QtGui.QLabel(self.groupBox_7)
        self.label_76.setEnabled(False)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_8.addWidget(self.label_76, 6, 3, 1, 1)
        self.modelSizeSuffix = QtGui.QLineEdit(self.groupBox_7)
        self.modelSizeSuffix.setObjectName(_fromUtf8("modelSizeSuffix"))
        self.gridLayout_8.addWidget(self.modelSizeSuffix, 4, 2, 1, 1)
        self.origin = QtGui.QLineEdit(self.groupBox_7)
        self.origin.setEnabled(False)
        self.origin.setObjectName(_fromUtf8("origin"))
        self.gridLayout_8.addWidget(self.origin, 6, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox_7)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_8.addWidget(self.label_45, 4, 3, 1, 1)
        self.posL = QtGui.QLineEdit(self.groupBox_7)
        self.posL.setObjectName(_fromUtf8("posL"))
        self.gridLayout_8.addWidget(self.posL, 10, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_7)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_8.addWidget(self.label_20, 11, 3, 1, 1)
        self.numObj = QtGui.QSpinBox(self.groupBox_7)
        self.numObj.setObjectName(_fromUtf8("numObj"))
        self.gridLayout_8.addWidget(self.numObj, 4, 4, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_7)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_8.addWidget(self.label_25, 4, 5, 1, 1)
        self.radius = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.radius.setMaximum(9999.0)
        self.radius.setObjectName(_fromUtf8("radius"))
        self.gridLayout_8.addWidget(self.radius, 10, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 7, 1, 3, 1)
        self.phi = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.phi.setMaximum(360.0)
        self.phi.setObjectName(_fromUtf8("phi"))
        self.gridLayout_8.addWidget(self.phi, 11, 4, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_7)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_8.addWidget(self.label_24, 11, 5, 1, 1)
        self.tabWidget_4.addTab(self.tabWidget_4Page1, _fromUtf8(""))
        self.tab_15 = QtGui.QWidget()
        self.tab_15.setObjectName(_fromUtf8("tab_15"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_15)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 0, 524, 261))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.DCoffsetIncrement = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.DCoffsetIncrement.setDecimals(3)
        self.DCoffsetIncrement.setMinimum(-99.99)
        self.DCoffsetIncrement.setObjectName(_fromUtf8("DCoffsetIncrement"))
        self.gridLayout.addWidget(self.DCoffsetIncrement, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_8)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.frameNum = QtGui.QSpinBox(self.groupBox_8)
        self.frameNum.setObjectName(_fromUtf8("frameNum"))
        self.gridLayout.addWidget(self.frameNum, 0, 2, 1, 1)
        self.label_255 = QtGui.QLabel(self.groupBox_8)
        self.label_255.setObjectName(_fromUtf8("label_255"))
        self.gridLayout.addWidget(self.label_255, 0, 3, 1, 1)
        self.speedIncrement = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.speedIncrement.setObjectName(_fromUtf8("speedIncrement"))
        self.gridLayout.addWidget(self.speedIncrement, 1, 0, 1, 1)
        self.label_156 = QtGui.QLabel(self.groupBox_8)
        self.label_156.setObjectName(_fromUtf8("label_156"))
        self.gridLayout.addWidget(self.label_156, 1, 1, 1, 1)
        self.speed = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.speed.setObjectName(_fromUtf8("speed"))
        self.gridLayout.addWidget(self.speed, 1, 2, 1, 1)
        self.label_155 = QtGui.QLabel(self.groupBox_8)
        self.label_155.setObjectName(_fromUtf8("label_155"))
        self.gridLayout.addWidget(self.label_155, 1, 3, 1, 1)
        self.gainIncrement = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.gainIncrement.setObjectName(_fromUtf8("gainIncrement"))
        self.gridLayout.addWidget(self.gainIncrement, 2, 0, 1, 1)
        self.label_157 = QtGui.QLabel(self.groupBox_8)
        self.label_157.setObjectName(_fromUtf8("label_157"))
        self.gridLayout.addWidget(self.label_157, 2, 1, 1, 1)
        self.wbad = QtGui.QSpinBox(self.groupBox_8)
        self.wbad.setObjectName(_fromUtf8("wbad"))
        self.gridLayout.addWidget(self.wbad, 2, 2, 1, 1)
        self.label_204 = QtGui.QLabel(self.groupBox_8)
        self.label_204.setObjectName(_fromUtf8("label_204"))
        self.gridLayout.addWidget(self.label_204, 2, 3, 1, 1)
        self.wbas = QtGui.QSpinBox(self.groupBox_8)
        self.wbas.setObjectName(_fromUtf8("wbas"))
        self.gridLayout.addWidget(self.wbas, 3, 2, 1, 1)
        self.label_205 = QtGui.QLabel(self.groupBox_8)
        self.label_205.setObjectName(_fromUtf8("label_205"))
        self.gridLayout.addWidget(self.label_205, 3, 3, 1, 1)
        self.humanDisplay = QtGui.QCheckBox(self.groupBox_8)
        self.humanDisplay.setObjectName(_fromUtf8("humanDisplay"))
        self.gridLayout.addWidget(self.humanDisplay, 4, 0, 1, 1)
        self.trajectoryUpdateInterval = QtGui.QSpinBox(self.groupBox_8)
        self.trajectoryUpdateInterval.setObjectName(_fromUtf8("trajectoryUpdateInterval"))
        self.gridLayout.addWidget(self.trajectoryUpdateInterval, 4, 2, 1, 1)
        self.label_108 = QtGui.QLabel(self.groupBox_8)
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.gridLayout.addWidget(self.label_108, 4, 3, 1, 2)
        self.mouseMode = QtGui.QCheckBox(self.groupBox_8)
        self.mouseMode.setObjectName(_fromUtf8("mouseMode"))
        self.gridLayout.addWidget(self.mouseMode, 5, 0, 1, 1)
        self.windowWidth = QtGui.QSpinBox(self.groupBox_8)
        self.windowWidth.setMaximum(9999)
        self.windowWidth.setObjectName(_fromUtf8("windowWidth"))
        self.gridLayout.addWidget(self.windowWidth, 5, 2, 1, 2)
        self.label_256 = QtGui.QLabel(self.groupBox_8)
        self.label_256.setObjectName(_fromUtf8("label_256"))
        self.gridLayout.addWidget(self.label_256, 5, 4, 1, 1)
        self.windowHeight = QtGui.QSpinBox(self.groupBox_8)
        self.windowHeight.setMaximum(9999)
        self.windowHeight.setObjectName(_fromUtf8("windowHeight"))
        self.gridLayout.addWidget(self.windowHeight, 6, 2, 1, 2)
        self.label_257 = QtGui.QLabel(self.groupBox_8)
        self.label_257.setObjectName(_fromUtf8("label_257"))
        self.gridLayout.addWidget(self.label_257, 6, 4, 1, 1)
        self.tabWidget_4.addTab(self.tab_15, _fromUtf8(""))
        self.layoutWidget = QtGui.QWidget(self.tab_7)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 10, 657, 24))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.loadWorld = QtGui.QCheckBox(self.layoutWidget)
        self.loadWorld.setObjectName(_fromUtf8("loadWorld"))
        self.horizontalLayout_2.addWidget(self.loadWorld)
        self.generateWorld = QtGui.QCheckBox(self.layoutWidget)
        self.generateWorld.setObjectName(_fromUtf8("generateWorld"))
        self.horizontalLayout_2.addWidget(self.generateWorld)
        self.quad = QtGui.QCheckBox(self.layoutWidget)
        self.quad.setObjectName(_fromUtf8("quad"))
        self.horizontalLayout_2.addWidget(self.quad)
        self.lockFps = QtGui.QCheckBox(self.layoutWidget)
        self.lockFps.setObjectName(_fromUtf8("lockFps"))
        self.horizontalLayout_2.addWidget(self.lockFps)
        self.loadNullModels = QtGui.QCheckBox(self.layoutWidget)
        self.loadNullModels.setObjectName(_fromUtf8("loadNullModels"))
        self.horizontalLayout_2.addWidget(self.loadNullModels)
        self.resetObject = QtGui.QCheckBox(self.layoutWidget)
        self.resetObject.setObjectName(_fromUtf8("resetObject"))
        self.horizontalLayout_2.addWidget(self.resetObject)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_64 = QtGui.QWidget()
        self.tab_64.setObjectName(_fromUtf8("tab_64"))
        self.groupBox = QtGui.QGroupBox(self.tab_64)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 566, 294))
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_363 = QtGui.QLabel(self.groupBox)
        self.label_363.setObjectName(_fromUtf8("label_363"))
        self.gridLayout_4.addWidget(self.label_363, 1, 2, 1, 1)
        self.label_372 = QtGui.QLabel(self.groupBox)
        self.label_372.setObjectName(_fromUtf8("label_372"))
        self.gridLayout_4.addWidget(self.label_372, 2, 4, 1, 1)
        self.interTrial = QtGui.QSpinBox(self.groupBox)
        self.interTrial.setObjectName(_fromUtf8("interTrial"))
        self.gridLayout_4.addWidget(self.interTrial, 3, 0, 1, 1)
        self.intraTrial = QtGui.QSpinBox(self.groupBox)
        self.intraTrial.setObjectName(_fromUtf8("intraTrial"))
        self.gridLayout_4.addWidget(self.intraTrial, 2, 0, 1, 1)
        self.signFlip = QtGui.QCheckBox(self.groupBox)
        self.signFlip.setObjectName(_fromUtf8("signFlip"))
        self.gridLayout_4.addWidget(self.signFlip, 5, 5, 1, 1)
        self.stepDur = QtGui.QSpinBox(self.groupBox)
        self.stepDur.setMinimum(-99)
        self.stepDur.setObjectName(_fromUtf8("stepDur"))
        self.gridLayout_4.addWidget(self.stepDur, 6, 0, 1, 1)
        self.label_362 = QtGui.QLabel(self.groupBox)
        self.label_362.setObjectName(_fromUtf8("label_362"))
        self.gridLayout_4.addWidget(self.label_362, 0, 2, 1, 1)
        self.label_366 = QtGui.QLabel(self.groupBox)
        self.label_366.setObjectName(_fromUtf8("label_366"))
        self.gridLayout_4.addWidget(self.label_366, 4, 1, 1, 2)
        self.startHeading = QtGui.QDoubleSpinBox(self.groupBox)
        self.startHeading.setDecimals(1)
        self.startHeading.setObjectName(_fromUtf8("startHeading"))
        self.gridLayout_4.addWidget(self.startHeading, 2, 3, 1, 1)
        self.nSteps = QtGui.QSpinBox(self.groupBox)
        self.nSteps.setObjectName(_fromUtf8("nSteps"))
        self.gridLayout_4.addWidget(self.nSteps, 0, 3, 1, 1)
        self.label_365 = QtGui.QLabel(self.groupBox)
        self.label_365.setObjectName(_fromUtf8("label_365"))
        self.gridLayout_4.addWidget(self.label_365, 3, 1, 1, 2)
        self.label_373 = QtGui.QLabel(self.groupBox)
        self.label_373.setObjectName(_fromUtf8("label_373"))
        self.gridLayout_4.addWidget(self.label_373, 3, 4, 1, 1)
        self.areaMode = QtGui.QCheckBox(self.groupBox)
        self.areaMode.setObjectName(_fromUtf8("areaMode"))
        self.gridLayout_4.addWidget(self.areaMode, 4, 5, 1, 1)
        self.stopDur = QtGui.QSpinBox(self.groupBox)
        self.stopDur.setObjectName(_fromUtf8("stopDur"))
        self.gridLayout_4.addWidget(self.stopDur, 5, 0, 1, 1)
        self.label_367 = QtGui.QLabel(self.groupBox)
        self.label_367.setObjectName(_fromUtf8("label_367"))
        self.gridLayout_4.addWidget(self.label_367, 5, 1, 1, 2)
        self.label_364 = QtGui.QLabel(self.groupBox)
        self.label_364.setObjectName(_fromUtf8("label_364"))
        self.gridLayout_4.addWidget(self.label_364, 2, 1, 1, 2)
        self.label_371 = QtGui.QLabel(self.groupBox)
        self.label_371.setObjectName(_fromUtf8("label_371"))
        self.gridLayout_4.addWidget(self.label_371, 1, 4, 1, 1)
        self.stepMode = QtGui.QCheckBox(self.groupBox)
        self.stepMode.setObjectName(_fromUtf8("stepMode"))
        self.gridLayout_4.addWidget(self.stepMode, 1, 5, 1, 1)
        self.label_368 = QtGui.QLabel(self.groupBox)
        self.label_368.setObjectName(_fromUtf8("label_368"))
        self.gridLayout_4.addWidget(self.label_368, 6, 1, 1, 2)
        self.orderFlip = QtGui.QCheckBox(self.groupBox)
        self.orderFlip.setObjectName(_fromUtf8("orderFlip"))
        self.gridLayout_4.addWidget(self.orderFlip, 6, 5, 1, 1)
        self.factorDur = QtGui.QDoubleSpinBox(self.groupBox)
        self.factorDur.setObjectName(_fromUtf8("factorDur"))
        self.gridLayout_4.addWidget(self.factorDur, 7, 0, 1, 1)
        self.gpMode = QtGui.QCheckBox(self.groupBox)
        self.gpMode.setObjectName(_fromUtf8("gpMode"))
        self.gridLayout_4.addWidget(self.gpMode, 0, 5, 1, 1)
        self.nReps = QtGui.QSpinBox(self.groupBox)
        self.nReps.setObjectName(_fromUtf8("nReps"))
        self.gridLayout_4.addWidget(self.nReps, 1, 3, 1, 1)
        self.label_369 = QtGui.QLabel(self.groupBox)
        self.label_369.setObjectName(_fromUtf8("label_369"))
        self.gridLayout_4.addWidget(self.label_369, 7, 1, 1, 2)
        self.durListGen = QtGui.QCheckBox(self.groupBox)
        self.durListGen.setObjectName(_fromUtf8("durListGen"))
        self.gridLayout_4.addWidget(self.durListGen, 2, 5, 1, 1)
        self.durList = QtGui.QLineEdit(self.groupBox)
        self.durList.setObjectName(_fromUtf8("durList"))
        self.gridLayout_4.addWidget(self.durList, 0, 0, 1, 2)
        self.headingListGen = QtGui.QCheckBox(self.groupBox)
        self.headingListGen.setObjectName(_fromUtf8("headingListGen"))
        self.gridLayout_4.addWidget(self.headingListGen, 3, 5, 1, 1)
        self.startDur = QtGui.QSpinBox(self.groupBox)
        self.startDur.setObjectName(_fromUtf8("startDur"))
        self.gridLayout_4.addWidget(self.startDur, 4, 0, 1, 1)
        self.headingRate = QtGui.QLineEdit(self.groupBox)
        self.headingRate.setObjectName(_fromUtf8("headingRate"))
        self.gridLayout_4.addWidget(self.headingRate, 1, 0, 1, 2)
        self.label_370 = QtGui.QLabel(self.groupBox)
        self.label_370.setObjectName(_fromUtf8("label_370"))
        self.gridLayout_4.addWidget(self.label_370, 0, 4, 1, 1)
        self.area = QtGui.QSpinBox(self.groupBox)
        self.area.setObjectName(_fromUtf8("area"))
        self.gridLayout_4.addWidget(self.area, 3, 3, 1, 1)
        self.imposeStimulus = QtGui.QCheckBox(self.tab_64)
        self.imposeStimulus.setGeometry(QtCore.QRect(10, 10, 141, 22))
        self.imposeStimulus.setObjectName(_fromUtf8("imposeStimulus"))
        self.tabWidget.addTab(self.tab_64, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_9.setGeometry(QtCore.QRect(40, 10, 252, 261))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.bagFullTopics = QtGui.QLineEdit(self.groupBox_9)
        self.bagFullTopics.setObjectName(_fromUtf8("bagFullTopics"))
        self.gridLayout_16.addWidget(self.bagFullTopics, 0, 0, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox_9)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_16.addWidget(self.label_47, 0, 1, 1, 1)
        self.bagTrajTopics = QtGui.QLineEdit(self.groupBox_9)
        self.bagTrajTopics.setObjectName(_fromUtf8("bagTrajTopics"))
        self.gridLayout_16.addWidget(self.bagTrajTopics, 1, 0, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBox_9)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_16.addWidget(self.label_48, 1, 1, 1, 1)
        self.race = QtGui.QComboBox(self.groupBox_9)
        self.race.setObjectName(_fromUtf8("race"))
        self.race.addItem(_fromUtf8(""))
        self.race.addItem(_fromUtf8(""))
        self.race.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.race, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_9)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_16.addWidget(self.label_6, 2, 1, 1, 1)
        self.emergence = QtGui.QDateEdit(self.groupBox_9)
        self.emergence.setObjectName(_fromUtf8("emergence"))
        self.gridLayout_16.addWidget(self.emergence, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_9)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_16.addWidget(self.label_7, 3, 1, 1, 1)
        self.boutNum = QtGui.QSpinBox(self.groupBox_9)
        self.boutNum.setProperty("value", 1)
        self.boutNum.setObjectName(_fromUtf8("boutNum"))
        self.gridLayout_16.addWidget(self.boutNum, 4, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_9)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_16.addWidget(self.label_12, 4, 1, 1, 1)
        self.fly = QtGui.QLineEdit(self.groupBox_9)
        self.fly.setObjectName(_fromUtf8("fly"))
        self.gridLayout_16.addWidget(self.fly, 5, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBox_9)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_16.addWidget(self.label_49, 5, 1, 1, 1)
        self.metaExpData = QtGui.QLineEdit(self.groupBox_9)
        self.metaExpData.setObjectName(_fromUtf8("metaExpData"))
        self.gridLayout_16.addWidget(self.metaExpData, 6, 0, 1, 1)
        self.label_50 = QtGui.QLabel(self.groupBox_9)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_16.addWidget(self.label_50, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_10)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 50, 424, 152))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_10.addWidget(self.label_14, 0, 1, 1, 1)
        self.playbackIncrement = QtGui.QSpinBox(self.groupBox_2)
        self.playbackIncrement.setObjectName(_fromUtf8("playbackIncrement"))
        self.gridLayout_10.addWidget(self.playbackIncrement, 0, 2, 1, 2)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_10.addWidget(self.label_16, 0, 4, 1, 1)
        self.captureStart = QtGui.QSpinBox(self.groupBox_2)
        self.captureStart.setObjectName(_fromUtf8("captureStart"))
        self.gridLayout_10.addWidget(self.captureStart, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_10.addWidget(self.label_15, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_10.addWidget(self.label_17, 1, 4, 1, 1)
        self.frameRecordPath = QtGui.QLineEdit(self.groupBox_2)
        self.frameRecordPath.setText(_fromUtf8(""))
        self.frameRecordPath.setObjectName(_fromUtf8("frameRecordPath"))
        self.gridLayout_10.addWidget(self.frameRecordPath, 3, 0, 1, 1)
        self.frameRecordPathBtn = QtGui.QPushButton(self.groupBox_2)
        self.frameRecordPathBtn.setObjectName(_fromUtf8("frameRecordPathBtn"))
        self.gridLayout_10.addWidget(self.frameRecordPathBtn, 3, 1, 1, 1)
        self.captureScale = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.captureScale.setObjectName(_fromUtf8("captureScale"))
        self.gridLayout_10.addWidget(self.captureScale, 0, 0, 1, 1)
        self.recordDur = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.recordDur.setObjectName(_fromUtf8("recordDur"))
        self.gridLayout_10.addWidget(self.recordDur, 1, 2, 1, 2)
        self.recordFps = QtGui.QSpinBox(self.groupBox_2)
        self.recordFps.setMaximum(200)
        self.recordFps.setObjectName(_fromUtf8("recordFps"))
        self.gridLayout_10.addWidget(self.recordFps, 3, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_10.addWidget(self.label_18, 3, 4, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.tab_10)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 239, 24))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_15 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.replayWorld = QtGui.QCheckBox(self.layoutWidget1)
        self.replayWorld.setObjectName(_fromUtf8("replayWorld"))
        self.gridLayout_15.addWidget(self.replayWorld, 0, 0, 1, 1)
        self.frameRecord = QtGui.QCheckBox(self.layoutWidget1)
        self.frameRecord.setEnabled(False)
        self.frameRecord.setObjectName(_fromUtf8("frameRecord"))
        self.gridLayout_15.addWidget(self.frameRecord, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_10, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_6)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 9, 881, 871))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.pausePlot = QtGui.QCheckBox(self.tab_2)
        self.pausePlot.setGeometry(QtCore.QRect(200, 750, 71, 22))
        self.pausePlot.setObjectName(_fromUtf8("pausePlot"))
        self.clearPlot = QtGui.QPushButton(self.tab_2)
        self.clearPlot.setGeometry(QtCore.QRect(109, 748, 85, 27))
        self.clearPlot.setAutoDefault(False)
        self.clearPlot.setDefault(False)
        self.clearPlot.setObjectName(_fromUtf8("clearPlot"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 531, 501))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.trajectoryLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.trajectoryLayout.setMargin(0)
        self.trajectoryLayout.setObjectName(_fromUtf8("trajectoryLayout"))
        self.resetView = QtGui.QPushButton(self.tab_2)
        self.resetView.setGeometry(QtCore.QRect(8, 748, 95, 27))
        self.resetView.setObjectName(_fromUtf8("resetView"))
        self.livePosition = QtGui.QLabel(self.tab_2)
        self.livePosition.setGeometry(QtCore.QRect(300, 520, 121, 81))
        self.livePosition.setObjectName(_fromUtf8("livePosition"))
        self.positionLabel = QtGui.QLabel(self.tab_2)
        self.positionLabel.setGeometry(QtCore.QRect(300, 500, 121, 21))
        self.positionLabel.setObjectName(_fromUtf8("positionLabel"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(610, 750, 121, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lcdServoAngle = QtGui.QLCDNumber(self.tab_2)
        self.lcdServoAngle.setGeometry(QtCore.QRect(320, 660, 71, 61))
        self.lcdServoAngle.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdServoAngle.setNumDigits(3)
        self.lcdServoAngle.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdServoAngle.setObjectName(_fromUtf8("lcdServoAngle"))
        self.label_23 = QtGui.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(330, 710, 121, 31))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.compassServo = QwtCompass(self.tab_2)
        self.compassServo.setGeometry(QtCore.QRect(357, 515, 340, 240))
        self.compassServo.setReadOnly(True)
        self.compassServo.setLineWidth(4)
        self.compassServo.setFrameShadow(QwtDial.Raised)
        self.compassServo.setDirection(QwtDial.CounterClockwise)
        self.compassServo.setObjectName(_fromUtf8("compassServo"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 508, 271, 241))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.histog = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.histog.setMargin(0)
        self.histog.setObjectName(_fromUtf8("histog"))
        self.lcdHeadingAngle = QtGui.QLCDNumber(self.tab_2)
        self.lcdHeadingAngle.setGeometry(QtCore.QRect(620, 710, 111, 41))
        self.lcdHeadingAngle.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdHeadingAngle.setNumDigits(3)
        self.lcdHeadingAngle.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdHeadingAngle.setObjectName(_fromUtf8("lcdHeadingAngle"))
        self.compassHeading = QwtCompass(self.tab_2)
        self.compassHeading.setGeometry(QtCore.QRect(446, 540, 160, 191))
        self.compassHeading.setReadOnly(True)
        self.compassHeading.setLineWidth(4)
        self.compassHeading.setDirection(QwtDial.CounterClockwise)
        self.compassHeading.setObjectName(_fromUtf8("compassHeading"))
        self.stateLabel = QtGui.QLabel(self.tab_2)
        self.stateLabel.setGeometry(QtCore.QRect(580, 0, 121, 21))
        self.stateLabel.setObjectName(_fromUtf8("stateLabel"))
        self.liveState = QtGui.QLabel(self.tab_2)
        self.liveState.setGeometry(QtCore.QRect(550, 0, 171, 461))
        self.liveState.setObjectName(_fromUtf8("liveState"))
        self.compassSlip = QwtCompass(self.tab_2)
        self.compassSlip.setGeometry(QtCore.QRect(480, 575, 91, 121))
        self.compassSlip.setReadOnly(True)
        self.compassSlip.setLineWidth(4)
        self.compassSlip.setDirection(QwtDial.CounterClockwise)
        self.compassSlip.setObjectName(_fromUtf8("compassSlip"))
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(640, 490, 121, 31))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.lcdSlipAngle = QtGui.QLCDNumber(self.tab_2)
        self.lcdSlipAngle.setGeometry(QtCore.QRect(640, 510, 71, 61))
        self.lcdSlipAngle.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdSlipAngle.setNumDigits(3)
        self.lcdSlipAngle.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdSlipAngle.setObjectName(_fromUtf8("lcdSlipAngle"))
        self.positionLabel_2 = QtGui.QLabel(self.tab_2)
        self.positionLabel_2.setGeometry(QtCore.QRect(450, 660, 61, 21))
        self.positionLabel_2.setObjectName(_fromUtf8("positionLabel_2"))
        self.positionLabel_3 = QtGui.QLabel(self.tab_2)
        self.positionLabel_3.setGeometry(QtCore.QRect(490, 640, 61, 21))
        self.positionLabel_3.setObjectName(_fromUtf8("positionLabel_3"))
        self.positionLabel_4 = QtGui.QLabel(self.tab_2)
        self.positionLabel_4.setGeometry(QtCore.QRect(420, 680, 61, 21))
        self.positionLabel_4.setObjectName(_fromUtf8("positionLabel_4"))
        self.trackFly = QtGui.QCheckBox(self.tab_2)
        self.trackFly.setGeometry(QtCore.QRect(540, 470, 111, 22))
        self.trackFly.setObjectName(_fromUtf8("trackFly"))
        self.label_33 = QtGui.QLabel(self.tab_2)
        self.label_33.setGeometry(QtCore.QRect(540, 440, 81, 29))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalSlider = QtGui.QSlider(self.tab_2)
        self.verticalSlider.setGeometry(QtCore.QRect(500, 30, 61, 421))
        self.verticalSlider.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.verticalSlider.setMinimum(-60)
        self.verticalSlider.setMaximum(40)
        self.verticalSlider.setSingleStep(2)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(False)
        self.verticalSlider.setInvertedControls(False)
        self.verticalSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.tabWidget, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        RhagGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RhagGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 741, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        RhagGUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(RhagGUI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        RhagGUI.setStatusBar(self.statusbar)

        self.retranslateUi(RhagGUI)
        self.tabWidget.setCurrentIndex(5)
        self.tabWidget1.setCurrentIndex(2)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.replayWorld, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.frameRecord.setEnabled)
        QtCore.QObject.connect(self.imposeStimulus, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox.setEnabled)
        QtCore.QObject.connect(self.frameRecord, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox_2.setEnabled)
        QtCore.QObject.connect(self.loadOdour, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox_3.setEnabled)
        QtCore.QObject.connect(self.loadWorld, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox_7.setEnabled)
        QtCore.QObject.connect(self.useOdourMask, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox_6.setEnabled)
        QtCore.QObject.connect(self.loadWind, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox_10.setEnabled)
        QtCore.QObject.connect(self.loadWind, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.windQuad.setEnabled)
        QtCore.QObject.connect(self.loadWind, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.label_8.setEnabled)
        QtCore.QObject.connect(self.loadWind, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.label_152.setEnabled)
        QtCore.QObject.connect(self.gain, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdGain.display)
        QtCore.QObject.connect(self.loadOdour, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.useOdourMask.setChecked)
        QtCore.QObject.connect(self.loadWind, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.windQuadOpen.setEnabled)
        QtCore.QObject.connect(self.loadWind, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.label_31.setEnabled)
        QtCore.QObject.connect(self.loadWind, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.windSpeed.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(RhagGUI)

    def retranslateUi(self, RhagGUI):
        RhagGUI.setWindowTitle(_translate("RhagGUI", "MainWindow", None))
        self.camParamBtn.setText(_translate("RhagGUI", "Camera Parameters", None))
        self.startVRBtn.setText(_translate("RhagGUI", "START VR", None))
        self.stopVRBtn.setText(_translate("RhagGUI", "STOP VR", None))
        self.wbadBtn.setText(_translate("RhagGUI", "Wing Beat Analyser", None))
        self.rqtBtn.setText(_translate("RhagGUI", "RQT plot", None))
        self.loadOdour.setText(_translate("RhagGUI", "Odour", None))
        self.label.setText(_translate("RhagGUI", "Loading String", None))
        self.label_2.setText(_translate("RhagGUI", "Gain", None))
        self.loadWind.setText(_translate("RhagGUI", "Wind", None))
        self.loadTrajectory.setText(_translate("RhagGUI", "Plot Trajectory", None))
        self.label_13.setText(_translate("RhagGUI", "max speed", None))
        self.groupBox_3.setTitle(_translate("RhagGUI", "Control Odour", None))
        self.odourBtn1.setText(_translate("RhagGUI", "Select odour 1", None))
        self.groupBox_6.setTitle(_translate("RhagGUI", "Odour Masks", None))
        self.odour3MaskBtn.setText(_translate("RhagGUI", "Select odour 3 Mask", None))
        self.odour1MaskBtn.setText(_translate("RhagGUI", "Select odour 1 Mask", None))
        self.odour4MaskBtn.setText(_translate("RhagGUI", "Select odour 4 Mask", None))
        self.odour2MaskBtn.setText(_translate("RhagGUI", "Select odour 2 Mask", None))
        self.odourBtn2.setText(_translate("RhagGUI", "Select odour 2", None))
        self.plotOdourQuad.setText(_translate("RhagGUI", "Plot odourQuad", None))
        self.label_9.setText(_translate("RhagGUI", "odourQuad", None))
        self.odourBtn4.setText(_translate("RhagGUI", "Select odour 4", None))
        self.odourBtn3.setText(_translate("RhagGUI", "Select odour 3", None))
        self.odourQuad.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">4 </span>items</p><p>[0, 0, 0, 0]</p></body></html>", None))
        self.odourQuad.setText(_translate("RhagGUI", "[]", None))
        self.label_11.setText(_translate("RhagGUI", "packetDur", None))
        self.useOdourMask.setText(_translate("RhagGUI", "Use Odour Masks", None))
        self.beepPathBtn.setText(_translate("RhagGUI", "Select Beep sound", None))
        self.useValve1.setText(_translate("RhagGUI", "Use valve 1", None))
        self.useValve2.setText(_translate("RhagGUI", "Use valve 2", None))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tabWidgetPage1), _translate("RhagGUI", "Odour", None))
        self.label_159.setText(_translate("RhagGUI", "nReps", None))
        self.label_160.setText(_translate("RhagGUI", "mode", None))
        self.pfStimDur_2.setText(_translate("RhagGUI", "pfStimDur", None))
        self.label_28.setText(_translate("RhagGUI", "pfPreStimDur", None))
        self.label_27.setText(_translate("RhagGUI", "pfPreStim", None))
        self.label_30.setText(_translate("RhagGUI", "pfPostStimDur", None))
        self.label_29.setText(_translate("RhagGUI", "pfPostStim", None))
        self.label_26.setText(_translate("RhagGUI", "pfStimList", None))
        self.pfMode.setItemText(0, _translate("RhagGUI", "ordered", None))
        self.pfMode.setItemText(1, _translate("RhagGUI", "randomRep", None))
        self.pfStimList.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">4 </span>items</p><p>[0, 0, 0, 0]</p></body></html>", None))
        self.pfStimList.setText(_translate("RhagGUI", "[16,4,1,0.25]", None))
        self.pfGenTimeSeries.setText(_translate("RhagGUI", "genTimeSeries", None))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tab_5), _translate("RhagGUI", "pf", None))
        self.groupBox_10.setTitle(_translate("RhagGUI", "Control Wind", None))
        self.windQuad.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">4 </span>items</p><p>[0, 0, 0, 0]</p></body></html>", None))
        self.windQuad.setText(_translate("RhagGUI", "[]", None))
        self.label_8.setText(_translate("RhagGUI", "windQuad", None))
        self.label_152.setText(_translate("RhagGUI", "windSpeed", None))
        self.windQuadOpen.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">4 </span>items</p><p>[0, 0, 0, 0]</p></body></html>", None))
        self.windQuadOpen.setText(_translate("RhagGUI", "[]", None))
        self.label_31.setText(_translate("RhagGUI", "windQuadOpen", None))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tabWidgetPage2), _translate("RhagGUI", "Wind", None))
        self.label_158.setText(_translate("RhagGUI", "fps", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("RhagGUI", "General", None))
        self.groupBox_4.setTitle(_translate("RhagGUI", "GroupBox", None))
        self.label_3.setText(_translate("RhagGUI", "DCoffset", None))
        self.label_22.setText(_translate("RhagGUI", "maxBoutDur", None))
        self.label_111.setText(_translate("RhagGUI", "maxDistance", None))
        self.playerInitPos.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">3 </span>items</p><p>(0, 0, 0)</p></body></html>", None))
        self.playerInitPos.setText(_translate("RhagGUI", "()", None))
        self.label_150.setText(_translate("RhagGUI", "playerInitPos", None))
        self.label_151.setText(_translate("RhagGUI", "playerInitH", None))
        self.camFOV.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">2 </span>items</p><p>(0, 0)</p></body></html>", None))
        self.camFOV.setText(_translate("RhagGUI", "()", None))
        self.label_147.setText(_translate("RhagGUI", "camFOV", None))
        self.camHpr.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">3 </span>items</p><p>(0, 0, 0)</p></body></html>", None))
        self.camHpr.setText(_translate("RhagGUI", "()", None))
        self.label_254.setText(_translate("RhagGUI", "camHpr", None))
        self.minWbas_2.setText(_translate("RhagGUI", "minWbas", None))
        self.maxWbas_2.setText(_translate("RhagGUI", "maxWbas", None))
        self.minSpeed_2.setText(_translate("RhagGUI", "minFlightSpeed", None))
        self.maxSpeed_3.setText(_translate("RhagGUI", "maxFlightSpeed", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("RhagGUI", "Player", None))
        self.groupBox_7.setTitle(_translate("RhagGUI", "GroupBox", None))
        self.randPos.setText(_translate("RhagGUI", "randPos", None))
        self.label_19.setText(_translate("RhagGUI", "posL", None))
        self.label_10.setText(_translate("RhagGUI", "radius", None))
        self.treeTexPathBtn.setText(_translate("RhagGUI", "treeTexPath", None))
        self.redTexPathBtn.setText(_translate("RhagGUI", "redTexPath", None))
        self.label_110.setText(_translate("RhagGUI", "obj2Scale", None))
        self.label_109.setText(_translate("RhagGUI", "obj1Scale", None))
        self.obj1PathBtn.setText(_translate("RhagGUI", "object 1", None))
        self.obj2PathBtn.setText(_translate("RhagGUI", "object 2", None))
        self.posR.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">2 </span>items</p><p>(0, 0)</p></body></html>", None))
        self.posR.setText(_translate("RhagGUI", "()", None))
        self.label_153.setText(_translate("RhagGUI", "obj1Z", None))
        self.label_149.setText(_translate("RhagGUI", "worldSize", None))
        self.label_154.setText(_translate("RhagGUI", "obj2Z", None))
        self.modelTextureMapBtn.setText(_translate("RhagGUI", "modelTextureMap", None))
        self.skyMapBtn.setText(_translate("RhagGUI", "skyMap", None))
        self.modelHeightMapBtn.setText(_translate("RhagGUI", "modelHeightMap", None))
        self.greenTexPathBtn.setText(_translate("RhagGUI", "greenTexPath", None))
        self.modelTextureMapNullBtn.setText(_translate("RhagGUI", "modelTextureMapNull", None))
        self.skyMapNullBtn.setText(_translate("RhagGUI", "skyMapNull", None))
        self.label_21.setText(_translate("RhagGUI", "bboxDist", None))
        self.label_76.setText(_translate("RhagGUI", "origin", None))
        self.origin.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">3 </span>items</p><p>(0, 0, 0)</p></body></html>", None))
        self.origin.setText(_translate("RhagGUI", "()", None))
        self.label_45.setText(_translate("RhagGUI", "modelSizeSuffix", None))
        self.posL.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">2 </span>items</p><p>(0, 0)</p></body></html>", None))
        self.posL.setText(_translate("RhagGUI", "()", None))
        self.label_20.setText(_translate("RhagGUI", "posR", None))
        self.label_25.setText(_translate("RhagGUI", "numObj", None))
        self.label_24.setText(_translate("RhagGUI", "phi", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tabWidget_4Page1), _translate("RhagGUI", "Objects", None))
        self.groupBox_8.setTitle(_translate("RhagGUI", "GroupBox", None))
        self.label_4.setText(_translate("RhagGUI", "DCoffset Incr.", None))
        self.label_255.setText(_translate("RhagGUI", "frameNum", None))
        self.label_156.setText(_translate("RhagGUI", "speedIncrement", None))
        self.label_155.setText(_translate("RhagGUI", "speed", None))
        self.label_157.setText(_translate("RhagGUI", "gainIncrement", None))
        self.label_204.setText(_translate("RhagGUI", "wbad", None))
        self.label_205.setText(_translate("RhagGUI", "wbas", None))
        self.humanDisplay.setText(_translate("RhagGUI", "humanDisplay", None))
        self.label_108.setText(_translate("RhagGUI", "trajectoryUpdateInterval", None))
        self.mouseMode.setText(_translate("RhagGUI", "mouseMode", None))
        self.label_256.setText(_translate("RhagGUI", "windowWidth", None))
        self.label_257.setText(_translate("RhagGUI", "windowHeight", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_15), _translate("RhagGUI", "Advanced", None))
        self.loadWorld.setText(_translate("RhagGUI", "load world", None))
        self.generateWorld.setText(_translate("RhagGUI", "generate world", None))
        self.quad.setText(_translate("RhagGUI", "quad", None))
        self.lockFps.setText(_translate("RhagGUI", "lockFps", None))
        self.loadNullModels.setText(_translate("RhagGUI", "loadNullModels", None))
        self.resetObject.setText(_translate("RhagGUI", "resetObject", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("RhagGUI", "World", None))
        self.groupBox.setTitle(_translate("RhagGUI", "Impose parameters", None))
        self.label_363.setText(_translate("RhagGUI", "headingRate", None))
        self.label_372.setText(_translate("RhagGUI", "startHeading", None))
        self.signFlip.setText(_translate("RhagGUI", "signFlip", None))
        self.label_362.setText(_translate("RhagGUI", "durList", None))
        self.label_366.setText(_translate("RhagGUI", "startDur", None))
        self.label_365.setText(_translate("RhagGUI", "interTrial", None))
        self.label_373.setText(_translate("RhagGUI", "area", None))
        self.areaMode.setText(_translate("RhagGUI", "areaMode", None))
        self.label_367.setText(_translate("RhagGUI", "stopDur", None))
        self.label_364.setText(_translate("RhagGUI", "intraTrial", None))
        self.label_371.setText(_translate("RhagGUI", "nReps", None))
        self.stepMode.setText(_translate("RhagGUI", "stepMode", None))
        self.label_368.setText(_translate("RhagGUI", "stepDur", None))
        self.orderFlip.setText(_translate("RhagGUI", "orderFlip", None))
        self.gpMode.setText(_translate("RhagGUI", "gpMode", None))
        self.label_369.setText(_translate("RhagGUI", "factorDur", None))
        self.durListGen.setText(_translate("RhagGUI", "durListGen", None))
        self.durList.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">x </span>items</p><p>[]</p></body></html>", None))
        self.durList.setText(_translate("RhagGUI", "[]", None))
        self.headingListGen.setText(_translate("RhagGUI", "headingListGen", None))
        self.headingRate.setToolTip(_translate("RhagGUI", "<html><head/><body><p>Add <span style=\" font-weight:600;\">x </span>items</p><p>[]</p></body></html>", None))
        self.headingRate.setText(_translate("RhagGUI", "[]", None))
        self.label_370.setText(_translate("RhagGUI", "nSteps", None))
        self.imposeStimulus.setText(_translate("RhagGUI", "Impose stimulus", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_64), _translate("RhagGUI", "Impose Stimulus", None))
        self.groupBox_9.setTitle(_translate("RhagGUI", "GroupBox", None))
        self.label_47.setText(_translate("RhagGUI", "bagFullTopics", None))
        self.label_48.setText(_translate("RhagGUI", "bagTrajTopics", None))
        self.race.setItemText(0, _translate("RhagGUI", "apple", None))
        self.race.setItemText(1, _translate("RhagGUI", "hawthorn", None))
        self.race.setItemText(2, _translate("RhagGUI", "unknown", None))
        self.label_6.setText(_translate("RhagGUI", "Race", None))
        self.label_7.setText(_translate("RhagGUI", "Emergence", None))
        self.label_12.setText(_translate("RhagGUI", "boutNum", None))
        self.label_49.setText(_translate("RhagGUI", "fly", None))
        self.label_50.setText(_translate("RhagGUI", "metaExpData", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("RhagGUI", "Record", None))
        self.groupBox_2.setTitle(_translate("RhagGUI", "Recording Options", None))
        self.label_14.setText(_translate("RhagGUI", "capture Downscale", None))
        self.label_16.setText(_translate("RhagGUI", "playback increment", None))
        self.label_15.setText(_translate("RhagGUI", "capture start", None))
        self.label_17.setText(_translate("RhagGUI", "record duration", None))
        self.frameRecordPathBtn.setText(_translate("RhagGUI", "record Path", None))
        self.label_18.setText(_translate("RhagGUI", "record fps", None))
        self.replayWorld.setText(_translate("RhagGUI", "replay world", None))
        self.frameRecord.setText(_translate("RhagGUI", "frameRecord", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("RhagGUI", "Replay", None))
        self.pausePlot.setText(_translate("RhagGUI", "Pause", None))
        self.clearPlot.setText(_translate("RhagGUI", "Clear Plot", None))
        self.resetView.setText(_translate("RhagGUI", "Reset View", None))
        self.livePosition.setText(_translate("RhagGUI", "None", None))
        self.positionLabel.setText(_translate("RhagGUI", "Position", None))
        self.label_5.setText(_translate("RhagGUI", "Heading Angle", None))
        self.label_23.setText(_translate("RhagGUI", "Servo Angle", None))
        self.stateLabel.setText(_translate("RhagGUI", "State", None))
        self.liveState.setText(_translate("RhagGUI", "None", None))
        self.label_32.setText(_translate("RhagGUI", "Slip Angle", None))
        self.positionLabel_2.setText(_translate("RhagGUI", "Heading", None))
        self.positionLabel_3.setText(_translate("RhagGUI", "Slip", None))
        self.positionLabel_4.setText(_translate("RhagGUI", "Servo", None))
        self.trackFly.setText(_translate("RhagGUI", "Track Fly", None))
        self.label_33.setText(_translate("RhagGUI", "Track Width", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("RhagGUI", "Tab 1", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("RhagGUI", "Page", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("RhagGUI", "Live", None))
from PyQt4.Qwt5.Qwt import QwtCompass, QwtDial; from pyqtgraph import PlotWidget

